### 기획자

우리 서비스를 사용할 사람들이 어떠한 사람인가?<br>
어떠한 기능을 원하는가?<br>

기획자로서, 필수적 역량은 '사용자의 니즈'를 파악하는 것이다.<br>
이 때, **데이터**에 기반해서 사용자의 마음을 알 수 있다.<br>
그래서 우리가 데이터 분석을 배우는 것이다.

국민은행 앱 사용자 리뷰 데이터 JSON 파일을 읽어와서 csv파일로 변환하기

In [1]:
import json
import pandas as pd

In [2]:
with open("./data/com_kbstar_kbbank.json", 'r', encoding="utf-8") as file:
    data = file.read()

In [3]:
data[:100]

'[\n    {\n        "사용자": "박성진 (홀리진)",\n        "별점": "4",\n        "리뷰": "리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면'

In [3]:
reviews = json.loads(data)
len(reviews)

2223

In [11]:
reviews[0]

{'사용자': '박성진 (홀리진)',
 '별점': '4',
 '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
 '날짜': '2025년 3월 2일',
 '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}

In [12]:
for key in reviews[0]:
    print(key)

사용자
별점
리뷰
날짜
개발자 응답

In [18]:
for review in reviews:
    print(review)
    
len(review)

{'사용자': '박성진 (홀리진)', '별점': '4', '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.', '날짜': '2025년 3월 2일', '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}
{'사용자': '윤태경', '별점': '5', '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.', '날짜': '2025년 1월 20일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': 'tae tae', '별점': '1', '리뷰': '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.', '날짜': '2025년 1월 14일', '개발자 응답': '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.'}
{'사용자': '정다우니', '별점': '5', '리뷰': '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.', '날짜': '2025년 1월 25일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': '우간능', '별점': '1', '리뷰': '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오', '날짜': '2025년 2월 1일', '개발자 응답': "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."}
{'사용자': '꾸꾸잉꾸', '별점': '1', '리뷰': '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...', '날짜': '2025년 2월 17일', '개발자 응답': '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.'}
{'사용자': '이이민우', '별점': '3', '리뷰': '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!', '날짜': '2025년 3월 3일', '개발자 응답': None}
{'사용자': '김수진', '별점': '3', '리뷰': '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ', '날짜': '2025년 1월 24일', '개발자 응답': '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.'}
{'사용자': '김영옥', '별점': '5', '리뷰': '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~', '날짜': '2025년 2월 11일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': '이욱', '별점': '5', '리뷰': '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..', '날짜': '2025년 3월 3일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': '김두영', '별점': '1', '리뷰': '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요', '날짜': '2025년 2월 24일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다."}
{'사용자': '훈', '별점': '1', '리뷰': '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄', '날짜': '2025년 2월 24일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다."}
{'사용자': '위윌왁휴', '별점': '1', '리뷰': '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.', '날짜': '2025년 3월 8일', '개발자 응답': None}
{'사용자': '김숏', '별점': '1', '리뷰': '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?', '날짜': '2025년 3월 12일', '개발자 응답': "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다."}
{'사용자': 'Sean Moon', '별점': '5', '리뷰': 'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)', '날짜': '2025년 3월 1일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': 'sprirea KTH', '별점': '1', '리뷰': '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.', '날짜': '2025년 2월 25일', '개발자 응답': None}
{'사용자': '깔린느', '별점': '5', '리뷰': '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^', '날짜': '2024년 12월 23일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!"}
{'사용자': '김유리', '별점': '5', '리뷰': '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.', '날짜': '2024년 12월 18일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다."}
{'사용자': '박성진 (홀리진)', '별점': '4', '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.', '날짜': '2025년 3월 2일', '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}
{'사용자': '윤태경', '별점': '5', '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.', '날짜': '2025년 1월 20일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': 'tae tae', '별점': '1', '리뷰': '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.', '날짜': '2025년 1월 14일', '개발자 응답': '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.'}
{'사용자': '정다우니', '별점': '5', '리뷰': '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.', '날짜': '2025년 1월 25일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': '우간능', '별점': '1', '리뷰': '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오', '날짜': '2025년 2월 1일', '개발자 응답': "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."}
{'사용자': '꾸꾸잉꾸', '별점': '1', '리뷰': '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...', '날짜': '2025년 2월 17일', '개발자 응답': '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.'}
{'사용자': '이이민우', '별점': '3', '리뷰': '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!', '날짜': '2025년 3월 3일', '개발자 응답': None}
{'사용자': '김수진', '별점': '3', '리뷰': '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ', '날짜': '2025년 1월 24일', '개발자 응답': '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.'}
{'사용자': '김영옥', '별점': '5', '리뷰': '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~', '날짜': '2025년 2월 11일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': '이욱', '별점': '5', '리뷰': '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..', '날짜': '2025년 3월 3일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': '김두영', '별점': '1', '리뷰': '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요', '날짜': '2025년 2월 24일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다."}
{'사용자': '훈', '별점': '1', '리뷰': '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄', '날짜': '2025년 2월 24일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다."}
{'사용자': '위윌왁휴', '별점': '1', '리뷰': '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.', '날짜': '2025년 3월 8일', '개발자 응답': None}
{'사용자': '김숏', '별점': '1', '리뷰': '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?', '날짜': '2025년 3월 12일', '개발자 응답': "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다."}
{'사용자': 'Sean Moon', '별점': '5', '리뷰': 'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)', '날짜': '2025년 3월 1일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': 'sprirea KTH', '별점': '1', '리뷰': '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.', '날짜': '2025년 2월 25일', '개발자 응답': None}
{'사용자': '깔린느', '별점': '5', '리뷰': '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^', '날짜': '2024년 12월 23일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!"}
{'사용자': '김유리', '별점': '5', '리뷰': '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.', '날짜': '2024년 12월 18일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다."}
{'사용자': '박성진 (홀리진)', '별점': '4', '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.', '날짜': '2025년 3월 2일', '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}
{'사용자': '윤태경', '별점': '5', '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.', '날짜': '2025년 1월 20일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': 'tae tae', '별점': '1', '리뷰': '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.', '날짜': '2025년 1월 14일', '개발자 응답': '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.'}
{'사용자': '정다우니', '별점': '5', '리뷰': '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.', '날짜': '2025년 1월 25일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': '우간능', '별점': '1', '리뷰': '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오', '날짜': '2025년 2월 1일', '개발자 응답': "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."}
{'사용자': '꾸꾸잉꾸', '별점': '1', '리뷰': '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...', '날짜': '2025년 2월 17일', '개발자 응답': '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.'}

5

In [17]:
for key in reviews[0]:
    temp = []
    print(temp)

[]
[]
[]
[]
[]

In [31]:
len(['박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경'])

20

In [46]:
for i in reviews[:20]:
    print (i)

{'사용자': '박성진 (홀리진)', '별점': '4', '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.', '날짜': '2025년 3월 2일', '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}
{'사용자': '윤태경', '별점': '5', '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.', '날짜': '2025년 1월 20일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': 'tae tae', '별점': '1', '리뷰': '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.', '날짜': '2025년 1월 14일', '개발자 응답': '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.'}
{'사용자': '정다우니', '별점': '5', '리뷰': '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.', '날짜': '2025년 1월 25일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}
{'사용자': '우간능', '별점': '1', '리뷰': '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오', '날짜': '2025년 2월 1일', '개발자 응답': "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다."}
{'사용자': '꾸꾸잉꾸', '별점': '1', '리뷰': '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...', '날짜': '2025년 2월 17일', '개발자 응답': '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.'}
{'사용자': '이이민우', '별점': '3', '리뷰': '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!', '날짜': '2025년 3월 3일', '개발자 응답': None}
{'사용자': '김수진', '별점': '3', '리뷰': '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ', '날짜': '2025년 1월 24일', '개발자 응답': '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.'}
{'사용자': '김영옥', '별점': '5', '리뷰': '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~', '날짜': '2025년 2월 11일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': '이욱', '별점': '5', '리뷰': '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..', '날짜': '2025년 3월 3일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': '김두영', '별점': '1', '리뷰': '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요', '날짜': '2025년 2월 24일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다."}
{'사용자': '훈', '별점': '1', '리뷰': '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄', '날짜': '2025년 2월 24일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다."}
{'사용자': '위윌왁휴', '별점': '1', '리뷰': '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.', '날짜': '2025년 3월 8일', '개발자 응답': None}
{'사용자': '김숏', '별점': '1', '리뷰': '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?', '날짜': '2025년 3월 12일', '개발자 응답': "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다."}
{'사용자': 'Sean Moon', '별점': '5', '리뷰': 'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)', '날짜': '2025년 3월 1일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^"}
{'사용자': 'sprirea KTH', '별점': '1', '리뷰': '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.', '날짜': '2025년 2월 25일', '개발자 응답': None}
{'사용자': '깔린느', '별점': '5', '리뷰': '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^', '날짜': '2024년 12월 23일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!"}
{'사용자': '김유리', '별점': '5', '리뷰': '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.', '날짜': '2024년 12월 18일', '개발자 응답': "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다."}
{'사용자': '박성진 (홀리진)', '별점': '4', '리뷰': '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.', '날짜': '2025년 3월 2일', '개발자 응답': '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.'}
{'사용자': '윤태경', '별점': '5', '리뷰': 'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.', '날짜': '2025년 1월 20일', '개발자 응답': "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"}

In [52]:
result

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경'],
 '별점': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5'],
 '리뷰': ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',
  '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..',
  '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요',
  '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄',
  '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.',
  '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?',
  'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)',
  '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.',
  '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^',
  '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.',
  '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.'],
 '날짜': ['2025년 3월 2일',
  '2025년 1월 20일',
  '2025년 1월 14일',
  '2025년 1월 25일',
  '2025년 2월 1일',
  '2025년 2월 17일',
  '2025년 3월 3일',
  '2025년 1월 24일',
  '2025년 2월 11일',
  '2025년 3월 3일',
  '2025년 2월 24일',
  '2025년 2월 24일',
  '2025년 3월 8일',
  '2025년 3월 12일',
  '2025년 3월 1일',
  '2025년 2월 25일',
  '2024년 12월 23일',
  '2024년 12월 18일',
  '2025년 3월 2일',
  '2025년 1월 20일'],
 '개발자 응답': ['고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
  '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
  "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
  '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
  None,
  '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
  None,
  "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  None,
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
  '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"]}

In [15]:
a = {}

In [19]:
a

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경'],
 '리뷰': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5']}

In [16]:
a["사용자"]=['박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경']

In [18]:
a["리뷰"] = ['4', '5', '1', '5', '1', '1', '3', '3', '5', '5', '1', '1', '1', '1', '5', '1', '5', '5', '4', '5']

In [13]:
b

['박성진 (홀리진)',
 '윤태경',
 'tae tae',
 '정다우니',
 '우간능',
 '꾸꾸잉꾸',
 '이이민우',
 '김수진',
 '김영옥',
 '이욱',
 '김두영',
 '훈',
 '위윌왁휴',
 '김숏',
 'Sean Moon',
 'sprirea KTH',
 '깔린느',
 '김유리',
 '박성진 (홀리진)',
 '윤태경']

In [ ]:
a["이름"] =

In [20]:
result = {}
for key in reviews[0]:
    temp = []   
    for review in reviews:
#         print(temp)
        temp.append(review[key])
    print(temp)
    result[key] = temp
# print(result)
len(result['별점'])

['박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', 'KTS Pastor', '조하진', 'J H', '김영진', 'Anne Sim', '유순', 'EunCheol Kweon', '송기복', '이영아', 'Yongbeom Moon', '이영주', '빛과소금', '김하늘', '밝고긍정적인거', '정현우', '임겸', 'Changwan “-” Yu']

2223

In [5]:
result

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경'],
 '별점': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5'],
 '리뷰': ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',
  '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..',
  '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요',
  '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄',
  '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.',
  '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?',
  'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)',
  '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.',
  '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^',
  '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.',
  '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.'],
 '날짜': ['2025년 3월 2일',
  '2025년 1월 20일',
  '2025년 1월 14일',
  '2025년 1월 25일',
  '2025년 2월 1일',
  '2025년 2월 17일',
  '2025년 3월 3일',
  '2025년 1월 24일',
  '2025년 2월 11일',
  '2025년 3월 3일',
  '2025년 2월 24일',
  '2025년 2월 24일',
  '2025년 3월 8일',
  '2025년 3월 12일',
  '2025년 3월 1일',
  '2025년 2월 25일',
  '2024년 12월 23일',
  '2024년 12월 18일',
  '2025년 3월 2일',
  '2025년 1월 20일'],
 '개발자 응답': ['고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
  '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
  "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
  '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
  None,
  '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
  None,
  "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  None,
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
  '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"]}

In [7]:
temp

['고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
 '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
 None,
 '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
 None,
 "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 None,
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
 '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
 '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
 None,
 '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
 None,
 "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 None,
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
 '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
 '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
 None,
 '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
 None,
 "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 None,
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
 '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
 '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
 None,
 '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
 None,
 "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 None,
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
 '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
 '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
 None,
 '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
 None,
 "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 None,
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
 "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
 '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
 "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
 '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
 None,
 '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
 "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",

In [21]:
df = pd.DataFrame(result)
df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

In [22]:
len(result['별점'])

2223

In [20]:
reviews[0].keys()

dict_keys(['사용자', '별점', '리뷰', '날짜', '개발자 응답'])

In [23]:
# 내가 이해하는 수준으로

name = []
rate = []
comment = []
days = []
reply = []

In [24]:
review_info = dict(
    사용자=name, 
    별점=rate, 
    리뷰=comment, 
    날짜=days, 
    개발자응답=reply  # 띄어쓰기 제거
)

In [25]:
review_info

{'사용자': [], '별점': [], '리뷰': [], '날짜': [], '개발자응답': []}

In [26]:
for item in reviews[:20]:
    name.append(item['사용자'])
    rate.append(item['별점'])
    comment.append(item['리뷰'])
    days.append(item['날짜'])
    reply.append(item['개발자 응답'])
    
review_info = dict(사용자=name, 별점=rate, 리뷰=comment, 날짜=days, 개발자응답=reply)
review_info

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경'],
 '별점': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5'],
 '리뷰': ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',
  '앱에서 환전할 때에 국민은행 인증서를 갖고 있으면 수수료를 10프로 정도 할인 받을 수 있다고 나오는데, 등록한게 없어서 외화에 따라서 최대 80프로까지 나오는데.. 수수료가 2천원 이상의 차액이 나오면 인증서를 받는 것을 추천합니다. 대략 600 달라 또는 500 유로 이상.. 환전하면 될 듯하네요. 2025년 3월 3일 환전 기준 환율..',
  '리뷰 잘 안쓰는데 쓰게 만드네요 언제부터인가 계속 오류 떠서 들어가지 못해서 맘먹고 업데이트, 지우고 새로 설치 했는데 계속 오류라고 뜸. 로그인이 되어야 쓰지 한참 로딩되더니 오류라고 창이 뜨고 먹통... 주거래은행을 바꾸던지 해야겠어요 다른 리뷰 보니 저만 그런게 아니더라고요',
  '진짜 이런 뭣같은 은행어플은 처음봄 암호 잊어버려서 찾으려니까 계좌번호 복붙도 안되게 해놓고 인증서 없으면 기존 암호를 입력해서 찾아야하는데 기본 암호를 모르니 암호를 찾아서 바꾸려는건데 어떡하라는건지? 어찌저찌 바꾸려니까 비밀번호 여러번 틀린거 오류 해제를 하라는데 오류해제 탭도 안 보임 ㅋㅋㅋㅋ 진짜 답대가리가 없는 수준. 돈 받아쳐먹고 이런거 할 생각은 못하나봄',
  '빗썸때문에 강제로 왔는데 휴면계좌 풀려면 OTP있어야 하고 OTP를 발급하려면 정상 계좌가 있어야되네요? 예전에 KB쓰다가 어플이 너무 불친절해서 다른 은행으로 옮겼는데 역시 KB는. KB다. 최악의 경험만 주는 KB.',
  '진짜 쓰레기같은 앱임. 이체하려고하면 계속 재방문을 환영합니다 뜨면서 이체가 안됨. 권유직원 입력 안하면 이체 못하게 막아놓은건가? 의심됨 이체만 안되고 다른건 잘 되는거 같은데 왜 이체를 막아놓는건지?',
  'UI가 깔끔하고 이용 과정에서 페이지 마다 이동 속도가 빠르고 매끄럽습니다. (타 은행 인터넷 뱅킹 어플 대비)',
  '나를 위한 쉽고 편한????. 앱 깔고. 로그인하는거부터 도전과 고행인데 쉽고 편한이라.........앱 로그인 하려다 포기했다. .KT사용자이고 금융관리유심인지 깔려있는데 인식안된다고 진행이 안된다.',
  '이제 다중 로그인이 안되는건가요? 주로 남편 계좌로 이체를 많이 하고 확인 해야하는것도 많은데.. 기존에 알림 설정이 되어있어 남편 계좌 알림은 오는데. 들어가면 제 로그인으로 자동로그인이 되고. 남편 계좌 로그인이 안되서 볼수 없어 불편하네요.ㅜㅜ 다달이 이체해야 하고 확인도 해야 하는데..자동 로그인 되는게 너무 불편합니다. 전 제 계좌를 잘 사용 안해서 개선된게 너무 불편하네요. 제 계좌 로그아웃 해도 다시 접속하면 제 계좌로 자동 로그인 되고..ㅜㅜ 각각 로그인. 할수 있게 개선 좀 해 주세요. 감사합니다^^ 덕분에 자동 로그인 안되게 설정 했습니다. 따뜻한 연말 보내세요^^',
  '안내글 너무 감사합니다. 제가 휴대폰 설정에서 캐시삭제하는건 이해하고 순서대로 따라하여서 캐시 삭제 하였는데요. 두번째는 아직 잘 못따라하겠네요~ 제 휴대폰 플레이스토어 KB스타뱅킹 업데이트 버튼이 활성되지 않네요~ 계속 안되면 네이버에 아이디 올려서 도움받아야 겠네요~ 감사합니다 22/12/18 글올리고 이후에 접속이 잘되어서 전화 문의 드리지 않았는데요 오늘또 접속안되네요 24/11/20 안녕하세요 앱이 아직 들어가지지 않는데요 전화상담 해야할까요? 22/11/28 챗봇 상담 친절하게 잘알려주셔서 감사합니다.',
  '리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.'],
 '날짜': ['2025년 3월 2일',
  '2025년 1월 20일',
  '2025년 1월 14일',
  '2025년 1월 25일',
  '2025년 2월 1일',
  '2025년 2월 17일',
  '2025년 3월 3일',
  '2025년 1월 24일',
  '2025년 2월 11일',
  '2025년 3월 3일',
  '2025년 2월 24일',
  '2025년 2월 24일',
  '2025년 3월 8일',
  '2025년 3월 12일',
  '2025년 3월 1일',
  '2025년 2월 25일',
  '2024년 12월 23일',
  '2024년 12월 18일',
  '2025년 3월 2일',
  '2025년 1월 20일'],
 '개발자응답': ['고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
  '안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증명서 발급 담당자에게 전달하여 개선여부를 검토하도록 하겠습니다. KB스타뱅킹은 앞으로도 고객님의 의견을 귀기울이며 보다 편리한 서비스를 제공할 수 있도록 하겠습니다. 이용에 불편을 드려 대단히 죄송합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!",
  "고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호, 계좌비밀번호 등의 중요정보 입력 시 보안을 위해 마스킹 처리하고 있습니다. 또한, 입력하는 글자가 타인에게 노출되는 것을 방지하기 위해 고객님이 입력한 버튼과 랜덤으로 다른 버튼을 같이 표시하고 있으며, 실제로 2개 버튼이 함께 입력되는 것은 아닙니다. 2개 버튼이 눌려지는 것처럼 보이는 것은 정상이니, 크게 신경쓰지 마시고 고객님의 비밀번호를 정확히 입력해 주시면 정상적으로 이용하실 수 있습니다. 추가 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리]로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다.",
  '고객님 안녕하세요. 현재 KB스타뱅킹/인터넷뱅킹 거래가 정상화 되었습니다. 이용에 불편을 드려 진심으로 죄송합니다.',
  None,
  '고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 1.24(금) KB스타뱅킹의 KB매일걷기 사용 고객이 급증함에 따라 일시적으로 신규 사용자가 앱에 접근할 수 있는 속도가 제한되는 현상이 발생하였습니다. 현재 속도제한을 늘려 정상적으로 서비스 이용이 가능하도록 조치 진행중이며, 빠른 시일내에 정상화할 예정입니다. 일시적으로 KB매일걷기 서비스 제공이 지연된 점 고객님께 양해를 부탁드립니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  "고객님 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 다만, 남겨주신 내용만으로는 고객정보 확인이 어려워 오류 원인을 정확히 파악하기 어려운 상황입니다. 이 점 너그러운 이해를 부탁드리며, 인터넷뱅킹ID와 오류창이 뜨는 화면 캡쳐본, 오류가 발생하는 시점 등 세부내용을 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시면 파악 후 안내드리겠습니다. 감사합니다.",
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 계좌비밀번호 변경/오류해제를 원하시는 경우 [전체메뉴>가입상품관리>계좌설정]에서 이용하실 수 있습니다. 계좌비밀번호는 연속해서 4회 오류 시 이용제한 상태가 되어 '오류해제'를 하실 수 있습니다. 만일 4회 미만 오류 상태일 경우에는 '계좌비밀번호 변경' 거래를 해주셔야 합니다. 기존 계좌비밀번호를 아시는 경우 '기존 비밀번호 입력' 진행을 하실 수 있으며, 기존 계좌비밀번호를 모르시는 경우에는 '신분증 촬영' 진행이 필요합니다. 감사합니다.",
  None,
  "고객님, 안녕하세요. KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 재방문 환영 화면은 12개월 이상 인터넷/KB스타뱅킹을 통한 이체거래 실적이 없어 장기미사용 이체제한 등록이 된 상태에서 KB스타뱅킹 로그인을 할 경우 보여지는 재방문 환영 화면이 보여집니다. 권유직원이 없으시다면 권유직원 선택 영역에서 '없음'을 선택해 주시면 재등록을 진행하실 수 있습니다. 번거로우시겠지만 이 점 참고하여 다시 한번 거래를 부탁드리겠습니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다. 감사합니다.",
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버포스트 'KB스타뱅킹 앱리뷰' 고객의 목소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해주시기 바랍니다! 감사합니다^^",
  None,
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님께서 남겨주신 내용만으로 정확한 정보 확인이 어려운 점 양해를 부탁드리며, 먼저 문의주신 '자동 로그인 해제하는 방법'을 안내드리도록 하겠습니다. [KB스타뱅킹 메뉴 > 환경설정 > 로그인 설정]에서 '앱 열때마다 로그인'을 선택하여 적용하시면, 로그인을 할 때마다 인증절차를 거쳐 로그인 하게되오니 설정을 변경해보시기 바랍니다. 앱 이용 중 문의사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다. 감사합니다!",
  "안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱구동이 원활하지 않으시다면 보편적인 조치사항을 안내드리겠습니다. ①핸드폰 설정>애플리케이션>KB스타뱅킹 > 캐시 삭제 ② KB스타뱅킹 캐시/쿠키 삭제: 메뉴 > 앱 환경설정 > 캐시/쿠키삭제 진행을 부탁드립니다. 동일한 오류가 반복되신다면, 번거로우시겠지만 뱅킹 ID를 [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리]로 남겨주시길 부탁드리겠습니다. 빠르게 확인 후 안내드리도록 하겠습니다. 감사합니다.",
  '고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으나, 고객님께서 편리하게 이용하셨던 점이 충분히 이해되어 ATM입금 기능 도입 여부에 대해 검토해 보도록 하겠습니다. 다만, 새로운 서비스를 도입하기 위해서는 타행 시장조사, 요건 분석 및 개발 범위 등 검토되어야할 사항이 많아 다소 많은 시일이 소요될 수 있는 점 양해 부탁드립니다. 마지막으로 당행 자동화기기에서는 통장/카드없이 무통장 입금 서비스를 이용하실 수 있는 방법도 있으니 거래에 참고 부탁드리겠습니다.(*이용한도: 1회 50만원, 1일 100만원) 더욱 편리한 서비스를 제공하는 KB스타뱅킹이 되겠습니다. 감사합니다.',
  "고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹은 고객님께서 항상 편리하게 사용하실 수 있도록 최선을 다하겠습니다! 앱 이용 중 개선사항이 있으시다면, [네이버 포스트 'KB스타뱅킹 앱리뷰' 고객의 소리] 또는 고객센터(1588-9999>0>3번)로 언제든 편하게 말씀해 주시기 바랍니다♥ 감사합니다!"]}

In [31]:
result = {}

for key in reviews[0]:
    value_list = []
    for item in reviews:
        value_list.append(item[key])
    print(key, value_list)
    result[key] = value_list

사용자 ['박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', '박성진 (홀리진)', '윤태경', 'tae tae', '정다우니', '우간능', '꾸꾸잉꾸', '이이민우', '김수진', '김영옥', '이욱', '김두영', '훈', '위윌왁휴', '김숏', 'Sean Moon', 'sprirea KTH', '깔린느', '김유리', 'soy', '권태윤', '보라랏', 'back to the future', 'IlIII lll', 'BK', '반짝반짝빛나는', 'ᄋᄋᄋ', 'o oo', '박정숙', '한준희', 'Mata Ivanov', 'J제이', 'Sophia Joo', '무나다', '김지유03', '클로브', '구윤아', 'JH Park', 'Hodol Azbai', '샤머니즘', '신동', '최지영', '어서오고', '이점식', '몰?', '굿마운틴', '오우석', 'seonwoong choi', '_데헷', '죄묘고상스', '김세호', '월코비트', '강석근', 'Noqu', '김성찬', '김플라워', 'Jason852', '정하늘', '김연홍', '뇌절연구소', 'YJ S', '__', 'huihwan kim', '천벌의토템', '최은경', 'SU영감', '박예솔', '미카엘', 'Youngmi Son', 'Y', 'M곰이 (웅이)', '강재인', 'sa ro', '수혁', 'IW P.', '최경국', '안준서', 'Es k', '안유진', 'kcc1330 k', '그니그니', '지성기', '석박행', 'alice noh', '김대성', '김동영', '안덕룡', '양성민', 'chan gyu maeng', '김부영', 'Chung su Lee', '김상호', '최원옥', '강남진', '최홍준', '유영광 (Sam)', '민유빈', '*STELLA*', 'Wolf NB', 'KTS Pastor', '조하진', 'J H', '김영진', 'Anne Sim', '유순', 'EunCheol Kweon', '송기복', '이영아', 'Yongbeom Moon', '이영주', '빛과소금', '김하늘', '밝고긍정적인거', '정현우', '임겸', 'Changwan “-” Yu']

In [14]:
result

{'사용자': ['박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  'seonwoong choi',
  '_데헷',
  '죄묘고상스',
  '김세호',
  '월코비트',
  '강석근',
  'Noqu',
  '김성찬',
  '김플라워',
  'Jason852',
  '정하늘',
  '김연홍',
  '뇌절연구소',
  'YJ S',
  '__',
  'huihwan kim',
  '천벌의토템',
  '최은경',
  'SU영감',
  '박예솔',
  '미카엘',
  'Youngmi Son',
  'Y',
  'M곰이 (웅이)',
  '강재인',
  'sa ro',
  '수혁',
  'IW P.',
  '최경국',
  '안준서',
  'Es k',
  '안유진',
  '박성진 (홀리진)',
  '윤태경',
  'tae tae',
  '정다우니',
  '우간능',
  '꾸꾸잉꾸',
  '이이민우',
  '김수진',
  '김영옥',
  '이욱',
  '김두영',
  '훈',
  '위윌왁휴',
  '김숏',
  'Sean Moon',
  'sprirea KTH',
  '깔린느',
  '김유리',
  'soy',
  '권태윤',
  '보라랏',
  'back to the future',
  'IlIII lll',
  'BK',
  '반짝반짝빛나는',
  'ᄋᄋᄋ',
  'o oo',
  '박정숙',
  '한준희',
  'Mata Ivanov',
  'J제이',
  'Sophia Joo',
  '무나다',
  '김지유03',
  '클로브',
  '구윤아',
  'JH Park',
  'Hodol Azbai',
  '샤머니즘',
  '신동',
  '최지영',
  '어서오고',
  '이점식',
  '몰?',
  '굿마운틴',
  '오우석',
  ...],
 '별점': ['4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  '5',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '5',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '2',
  '4',
  '1',
  '3',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '4',
  '2',
  '1',
  '5',
  '4',
  '5',
  '1',
  '5',
  '1',
  '1',
  '3',
  '3',
  '5',
  '5',
  '1',
  '1',
  '1',
  '1',
  '5',
  '1',
  '5',
  '5',
  '1',
  '1',
  '3',
  '2',
  '1',
  '1',
  '1',
  '1',
  '2',
  '5',
  '1',
  '1',
  '1',
  '4',
  '1',
  '1',
  '5',
  '1',
  '1',
  '1',
  '1',
  '3',
  '2',
  '1',
  '5',
  '1',
  '5',
  '3',
  ...],
 '리뷰': ['리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 카드를 가지고 다니지 않게 되는 편리한 금융생활을 누릴 수 있었는데 리브넥스트의 종료로 더 이상 모바일에서는 ATM에서 현금 입금을 할 수 없게 됐습니다. 이 기능을 없애게 된 이유가 있나요? 출금 기능만 남았던데 입금 기능을 만들어주시면 좋겠습니다.',
  'KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. 가입 과정은 간편하고 빠르게 진행되었으며, 온라인으로 모든 절차를 처리할 수 있어 편리했습니다. 특히, 모바일 앱의 사용자 인터페이스가 직관적이어서 처음 사용하는 사람도 쉽게 이해할 수 있었습니다. 계좌 개설 후에는 다양한 금융 서비스가 제공되어 더욱 유용했습니다. 특히 실시간 거래 내역 확인과 간편한 송금 서비스가 매우 마음에 들었습니다. 또한, 다양한 금융 상품에 쉽게 접근할 수 있어 자산 관리를 할 때 큰 도움이 되었습니다. 고객 서비스도 만족스러웠습니다. 문의사항이 있을 때 신속하게 응대해 주었고, 필요한 정보도 쉽게 얻을 수 있었습니다. 보안 측면에서도 안심할 수 있었고, 다양한 인증 절차가 있어 개인 정보 보호에 대한 걱정이 줄어들었습니다. 종합적으로 KB스타뱅킹 입출금계좌는 편리함과 효율성을 모두 갖춘 서비스로, 앞으로도 지속적으로 이용할 계획입니다.',
  '타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가기를 누르면 이전페이지가 아니라 처음페이지로 돌아가버림. 예전에 비해 전체적으로 발전하긴 했지만 예전 사용자경험수준이 너무나 처참했기에 타은행대비 아직 갈 길이 멀다고 생각함.',
  '설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 갑자기 다 날아가버린듯한 생각에 속으로 욕을 해가며 다시 접속했는데요, 진행중이었던 정보를 이어할 수 있도록 해놔서 한 숨 돌렸네요. 보안상 절차가 까다로운 듯 했지만 크게 막힘없이 잘 할 수 있었습니다.',
  '왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로 쓸수가 없고 이것땜에 못하는게 한두가지가 아니에요 아님 차라리 비번이 보이게라도 해줘서 이게 틀린건지 아닌지 확인이라도 시켜주던가 자꾸 두개씩 눌려서 어느걸로 비번이 쳐졌는지도 모릅니다 걍 은행 키보드를 없애고 핸폰 키보드를 쓰게해주던가 해주십시오',
  '2/15부터 로그인 아예 안됨. 뱅킹 업무 계속 못보고 있어서 짜증 인증서 로그인 안되고 캐시 삭제하라는거 다 삭제해도 로그인안돼서 아예 삭제하고 어플 다시 깜. 다시 까니 기존 등록되어있던 인증서 전부 사라져서 재등록해야한다고 떠서 짜증났지만 재등록함. 재등록하는 와중에 오류만 20번 넘게 뜸 핸드폰 인증하려면 뭐 어플 설치하라고 안내뜨고 짜증나서 죽는줄... 핸드폰 번호 인증은 오는데 화면은 오류라며 안넘어감. 거의 인증서 등록하는데만 20분 씀. 등록 겨우하고 다시 로그인 하는데 오류 뜨면서 로그인 할 수 없다고 뜸 국민 말고 다른 은행으로 갈아타려함 이정도로 로그인 안되고 개인정보 다 등록하고 신분증 등록해도 안된다고 뜨니 찜찜함...',
  '전체어플에서kb스타뱅킹 어플이 검색이 안되는 이슈가 있습니다. 플레이스토어에 들어와야 검색이 됩니다! 기본화면에 아이콘으로 추가할 수 없네요!',
  '갑자기 매일걷기 연동이안되고 구글로 다시연동하라는데 아무리해도 연동이안됩니다ㅡ앱이 로그인속도제한에 도달했다며 앱개발자에게 로그인속도 제한을 늘려달라고 요청하라고 뜹니다ㅡkbebiz에게 (앱개발자) 메일을 보내라고 뜨는데 평소에도 앱에 접속하지않으면 (매일 중간중간) 걷기연동이 꺼질때가있어요ㅜ 어디다 연락을해야하는걸까요ㅜ',
  '거래에 꼭 필요해서 계설하게 되었는데 편하게 집에서 어렵지않게 만들어지는게 너무 편리하네요 참고로 본인얼굴 인증할때 꼭 메이크업을 하세요~~ 계속 영상통화 연결한다고 하더니 오늘 약속이 있어 화장을하고 사진찍었는데 바로 본인확인이 되더군요 민증사진이랑 많이 달라보여 그런가요~~ ㅎㅎ 편하고 좋았습니다~~',

In [15]:
result_df = pd.DataFrame(result)
result_df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

별점은 숫자로 변환해서 넣기, 나머지는 특수문자 제거하기

In [5]:
reviews[2219]

{'사용자': '밝고긍정적인거',
 '별점': '1',
 '리뷰': '아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 타금융기관 어플도안됐겠죠.그러나 타금융기관인 신한은행어플,농협어플, 토스 다되는데 kb스타뱅킹어플만 지금안된다고요 이것만ㅡ이게 지금 제 문제입니까?? 제 네트워크 데이터문제예요? 타 금융기관어플은 결제고뭐고다되는데요?! " 응답코드(NT003) " " 은행서버의 일시적인 오류로 kb스타뱅킹과 연결이 끊어졌습니다 " 여기에 적힌말도 지금너네들문제라고 뜨잖아 너네들문제.네트워크, 데이터 문제가아닌 "은행서버의 일시적 오류" 라고 뜨잖아요장난치십니까 예? 당신네들 문제라고요당신네들. 17일날 업데이트하기전까지는 잘되다가 17일날업데이트 이후로 갑자기이렇게 앱창이 안열린단말입니다 갑자기ㅡ당장 고치세요진짜ㅡ업데이트 할때 대체 뭘건드렸길래 아ㅡ짜증나게 정말ㅡ너네지금 kb페이 앱도 결제안된다며? 화면 터치안되고ㅋ이것봐이래도 내문제라고?너네 업데이트할때 뭐잘못건드렸냐?kb페이앱도 업데이트이후로 안된다는데? 확인해봐라',
 '날짜': '2024년 12월 26일',
 '개발자 응답': '안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 경우 ①전원 재부팅 ②휴대폰 설정 > 애플리케이션 > KB스타뱅킹 > 캐시 삭제 ③휴대폰 설정 > 애플리케이션 > 크롬 > 저장공간 > 캐시 삭제 ④(Android System Webview가 설치되어 있는 경우) Google Play Store 접속 > Android System WebView 검색 > 제거를 진행해주시기 바랍니다. NT 오류의 경우 데이터와 Wifi 중 하나로만 연결 후 재시도를 부탁드리겠습니다. 동일한 오류 반복시 고객센터(1588-9999>0>3번)로 고객정보를 남겨주시면 빠르게 확인하여 안내드리겠습니다.'}

In [4]:
result = {}
for key in reviews[0]:
    temp = []
    for review in reviews:
        if key == '별점':
            temp.append(int(review[key]))
        else:
            temp2 = str(review[key]).replace("?", " ").replace("!", " ").replace(".", " ").replace(",", " ").replace("("," ").replace(")"," ")
            temp.append(temp2)
    result[key] = temp
len(result['별점'])

result_df = pd.DataFrame(result)
result_df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 홀리진,4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다 현금이나 실물 ...,2025년 3월 2일,고객님 안녕하세요 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으...
1,윤태경,5,KB스타뱅킹 입출금계좌를 가입한 후 전반적으로 매우 만족스러운 경험을 했습니다 ...,2025년 1월 20일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임 그리고 메뉴이동도 불편함 뒤로가...,2025년 1월 14일,안녕하세요 고객님 KB스타뱅킹 이용에 불편을 드려 죄송합니다 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요 KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만 네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요 KB스타뱅킹 이용에 불편을 드려 죄송합니다 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요 KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다 KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,고객님 안녕하세요 KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다 앱 이용 ...

In [46]:
df.info

<bound method DataFrame.info of                   사용자 별점                                                 리뷰  \
0           박성진 (홀리진)  4  리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...
1                 윤태경  5  KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...
2             tae tae  1  타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...
3                정다우니  5  설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...
4                 우간능  1  왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...
...               ... ..                                                ...
2218              김하늘  5        평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요
2219          밝고긍정적인거  1  아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...
2220              정현우  5                       안내가 정확해서 따라가면 다 되어서 너무 편리합니다
2221               임겸  5                    어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요
2222  Changwan “-” Yu  1  어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...

                 날짜                                             개발자 응답
0       2025년 3월 2일  고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으...
1      2025년 1월 20일  고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2      2025년 1월 14일  안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3      2025년 1월 25일  고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4       2025년 2월 1일  고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...             ...                                                ...
2218   2025년 3월 11일  고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219  2024년 12월 26일  안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220   2025년 3월 11일  고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221    2025년 3월 3일  고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222  2023년 10월 12일  고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ...

[2223 rows x 5 columns]>

In [50]:
result2 = {}

for review in reviews:
    for key, value in review.items():
        result2.setdefault(key, []).append(value)
        
result2_df = pd.DataFrame(result2)
result2_df

,사용자,별점,리뷰,날짜,개발자 응답
0,박성진 (홀리진),4,리브와 리브넥스트에서 사용했던 ATM입금 기능이 있으면 좋겠습니다. 현금이나 실물 ...,2025년 3월 2일,"고객님, 안녕하세요. 현재 KB스타뱅킹에서는 ATM입금 서비스를 제공하고 있지 않으..."
1,윤태경,5,"KB스타뱅킹 입출금계좌를 가입한 후, 전반적으로 매우 만족스러운 경험을 했습니다. ...",2025년 1월 20일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2,tae tae,1,타 은행대비 증명서발급이 매우 불편하고 제한적임. 그리고 메뉴이동도 불편함. 뒤로가...,2025년 1월 14일,안녕하세요 고객님. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 고객님의 의견을 증...
3,정다우니,5,설치 후 통장 개설 시 오류로 인해 종료가 됐었습니다. 하나하나 집중해서 잘했는데 ...,2025년 1월 25일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
4,우간능,1,왜 자꾸 앱 전용키보드를 쓸때 두개가 같이 눌리나요 그거땜에 로그인도 못하고 제대로...,2025년 2월 1일,고객님 안녕하세요. KB스타뱅킹 이용에 불편을 드려 진심으로 죄송합니다. 사용자암호...
...,...,...,...,...,...
2218,김하늘,5,평일 근무시간에 사진인증이 잘되는편 같습니다 업무시간 이외에도 잘되면 좋겠네요,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2219,밝고긍정적인거,1,아니이봐요지금 타금융기관어플은 다되는데 이것만안된다고요 이것만.네트워크문제였었으면 ...,2024년 12월 26일,안녕하세요. KB스타뱅킹 이용에 불편을 드려 죄송합니다. 앱 구동이 원활하지 않을 ...
2220,정현우,5,안내가 정확해서 따라가면 다 되어서 너무 편리합니다,2025년 3월 11일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2221,임겸,5,어플 UI가 알아보기 쉽고 사용하기 너무 편리해서 좋아요,2025년 3월 3일,고객님 안녕하세요! KB스타뱅킹을 이용해 주셔서 진심으로 감사드립니다. KB스타뱅킹...
2222,Changwan “-” Yu,1,어플 문제 때문에 월세도 못 내게 생겼습니다. 와이파이가 매우 잘 작동하는 상황에서...,2023년 10월 12일,"고객님, 안녕하세요! KB스타뱅킹 이용에 불편을 드려 대단히 죄송합니다. 앱 이용 ..."

# 치킨집 상권 분석

In [33]:
with open("./data/전국치킨집리스트.json", 'r', encoding="utf-8") as file:
    chicken = file.read()

In [34]:
data = json.loads(chicken)
len(data)

37

In [35]:
data[0]

{'header': {'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
  'columns': ['상가업소번호',
   '상호명',
   '지점명',
   '상권업종대분류코드',
   '상권업종대분류명',
   '상권업종중분류코드',
   '상권업종중분류명',
   '상권업종소분류코드',
   '상권업종소분류명',
   '표준산업분류코드',
   '표준산업분류명',
   '시도코드',
   '시도명',
   '시군구코드',
   '시군구명',
   '행정동코드',
   '행정동명',
   '법정동코드',
   '법정동명',
   'PNU코드',
   '대지구분코드',
   '대지구분명',
   '지번본번지',
   '지번부번지',
   '지번주소',
   '도로명코드',
   '도로명',
   '건물본번지',
   '건물부번지',
   '건물관리번호',
   '건물명',
   '도로명주소',
   '구우편번호',
   '신우편번호',
   '동정보',
   '층정보',
   '호정보',
   '경도',
   '위도'],
  'stdrYm': '202206',
  'resultCode': '00',
  'resultMsg': 'NORMAL SERVICE'},
 'body': {'items': [{'bizesId': '10027626',
    'bizesNm': '장모님치킨가창점',
    'brchNm': '가창점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '27',
    'ctprvnNm': '대구광역시',
    'signguCd': '27710',
    'signguNm': '달성군',
    'adongCd': '2771031000',
    'adongNm': '가창면',
    'ldongCd': '2771031024',
    'ldongNm': '가창면',
    'lnoCd': '2771031024101200001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 120,
    'lnoSlno': 1,
    'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
    'rdnmCd': '277103148001',
    'rdnm': '대구광역시 달성군 가창면 가창동로',
    'bldMnno': 6,
    'bldSlno': '',
    'bldMngNo': '2771031024101200004036858',
    'bldNm': '',
    'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
    'oldZipcd': '711861',
    'newZipcd': '42938',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.644458591419,
    'lat': 35.7826625402814},
   {'bizesId': '10098244',
    'bizesNm': '짱구피자치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41250',
    'signguNm': '동두천시',
    'adongCd': '4125056500',
    'adongNm': '불현동',
    'ldongCd': '4125010300',
    'ldongNm': '생연동',
    'lnoCd': '4125010300102680011',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 268,
    'lnoSlno': 11,
    'lnoAdr': '경기도 동두천시 생연동 268-11',
    'rdnmCd': '412503189006',
    'rdnm': '경기도 동두천시 못골로',
    'bldMnno': 30,
    'bldSlno': '',
    'bldMngNo': '4125010300102680011008557',
    'bldNm': '',
    'rdnmAdr': '경기도 동두천시 못골로 30',
    'oldZipcd': '483030',
    'newZipcd': '11320',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.06590346074,
    'lat': 37.9012616518346},
   {'bizesId': '10099459',
    'bizesNm': '쭈노치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41570',
    'signguNm': '김포시',
    'adongCd': '4157025300',
    'adongNm': '고촌읍',
    'ldongCd': '4157025324',
    'ldongNm': '고촌읍',
    'lnoCd': '4157025324105380008',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 538,
    'lnoSlno': 8,
    'lnoAdr': '경기도 김포시 고촌읍 신곡리 538-8',
    'rdnmCd': '415704427512',
    'rdnm': '경기도 김포시 고촌읍 장차로13번길',
    'bldMnno': 18,
    'bldSlno': '',
    'bldMngNo': '4157025324105380008019970',
    'bldNm': '',
    'rdnmAdr': '경기도 김포시 고촌읍 장차로13번길 18',
    'oldZipcd': '415811',
    'newZipcd': '10126',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.769859060814,
    'lat': 37.6037515030602},
   {'bizesId': '10136167',
    'bizesNm': '치킨뱅이',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42130',
    'signguNm': '원주시',
    'adongCd': '4213059000',
    'adongNm': '단계동',
    'ldongCd': '4213011000',
    'ldongNm': '단계동',
    'lnoCd': '4213011000108300006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 830,
    'lnoSlno': 6,
    'lnoAdr': '강원도 원주시 단계동 830-6',
    'rdnmCd': '421304457083',
    'rdnm': '강원도 원주시 금불3길',
    'bldMnno': 5,
    'bldSlno': '',
    'bldMngNo': '4213011000108300006022278',
    'bldNm': '',
    'rdnmAdr': '강원도 원주시 금불3길 5',
    'oldZipcd': '220938',
    'newZipcd': '26423',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.932025388709,
    'lat': 37.3483579547022},
   {'bizesId': '10136346',
    'bizesNm': '치킨월드율량점',
    'brchNm': '율량점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '43',
    'ctprvnNm': '충청북도',
    'signguCd': '43114',
    'signguNm': '청주시 청원구',
    'adongCd': '4311454000',
    'adongNm': '율량.사천동',
    'ldongCd': '4311410300',
    'ldongNm': '율량동',
    'lnoCd': '4311410300108060000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 806,
    'lnoSlno': '',
    'lnoAdr': '충청북도 청주시 청원구 율량동 806',
    'rdnmCd': '431144508043',
    'rdnm': '충청북도 청주시 청원구 공항로138번길',
    'bldMnno': 53,
    'bldSlno': '',
    'bldMngNo': '4311111500108060000045239',
    'bldNm': '',
    'rdnmAdr': '충청북도 청주시 청원구 공항로138번길 53',
    'oldZipcd': '363818',
    'newZipcd': '28328',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.487585541514,
    'lat': 36.6698161542425},
   {'bizesId': '10150151',
    'bizesNm': 'KFC',
    'brchNm': '수원이마트점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41113',
    'signguNm': '수원시 권선구',
    'adongCd': '4111368000',
    'adongNm': '권선2동',
    'ldongCd': '4111313700',
    'ldongNm': '권선동',
    'lnoCd': '4111313700111890000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1189,
    'lnoSlno': '',
    'lnoAdr': '경기도 수원시 권선구 권선동 1189',
    'rdnmCd': '411132012008',
    'rdnm': '경기도 수원시 권선구 경수대로',
    'bldMnno': 270,
    'bldSlno': '',
    'bldMngNo': '4111313700111890000027851',
    'bldNm': '할인점동',
    'rdnmAdr': '경기도 수원시 권선구 경수대로 270',
    'oldZipcd': '441713',
    'newZipcd': '16585',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.020087664145,
    'lat': 37.2501017782401},
   {'bizesId': '10186527',
    'bizesNm': '토마토두마리치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11440',
    'signguNm': '마포구',
    'adongCd': '1144063000',
    'adongNm': '신수동',
    'ldongCd': '1144011300',
    'ldongNm': '구수동',
    'lnoCd': '1144011300100700001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 70,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 마포구 구수동 70-1',
    'rdnmCd': '114403113023',
    'rdnm': '서울특별시 마포구 토정로',
    'bldMnno': 195,
    'bldSlno': 1,
    'bldMngNo': '1144011300100700001008546',
    'bldNm': '정우빌딩',
    'rdnmAdr': '서울특별시 마포구 토정로 195-1',
    'oldZipcd': '121130',
    'newZipcd': '04087',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.932820696234,
    'lat': 37.545508849345},
   {'bizesId': '10208331',
    'bizesNm': '페리카나치킨연수우성체인점',
    'brchNm': '연수우성체인점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28185',
    'signguNm': '연수구',
    'adongCd': '2818576200',
    'adongNm': '연수2동',
    'ldongCd': '2818510300',
    'ldongNm': '연수동',
    'lnoCd': '2818510300106340000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 634,
    'lnoSlno': '',
    'lnoAdr': '인천광역시 연수구 연수동 634',
    'rdnmCd': '281853152021',
    'rdnm': '인천광역시 연수구 원인재로',
    'bldMnno': 180,
    'bldSlno': '',
    'bldMngNo': '2818510300106340000007257',
    'bldNm': '연수우성2차아파트',
    'rdnmAdr': '인천광역시 연수구 원인재로 180',
    'oldZipcd': '406765',
    'newZipcd': '21931',
    'dongNo': '',
    'flrNo': '2',
    'hoNo': '',
    'lon': 126.683928104747,
    'lat': 37.4122665635834},
   {'bizesId': '10208355',
    'bizesNm': '페리카나치킨벽산분점',
    'brchNm': '벽산분점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42130',
    'signguNm': '원주시',
    'adongCd': '4213059000',
    'adongNm': '단계동',
    'ldongCd': '4213011000',
    'ldongNm': '단계동',
    'lnoCd': '4213011000108130012',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 813,
    'lnoSlno': 12,
    'lnoAdr': '강원도 원주시 단계동 813-12',
    'rdnmCd': '421304457083',
    'rdnm': '강원도 원주시 금불3길',
    'bldMnno': 34,
    'bldSlno': '',
    'bldMngNo': '4213011000108130012022273',
    'bldNm': '',
    'rdnmAdr': '강원도 원주시 금불3길 34',
    'oldZipcd': '220938',
    'newZipcd': '26423',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.93187697793,
    'lat': 37.3502141596654},
   {'bizesId': '10208360',
    'bizesNm': '페리카나치킨',
    'brchNm': '송천점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '45',
    'ctprvnNm': '전라북도',
    'signguCd': '45113',
    'signguNm': '전주시 덕진구',
    'adongCd': '4511364100',
    'adongNm': '송천1동',
    'ldongCd': '4511312100',
    'ldongNm': '송천동1가',
    'lnoCd': '4511312100101070143',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 107,
    'lnoSlno': 143,
    'lnoAdr': '전라북도 전주시 덕진구 송천동1가 107-143',
    'rdnmCd': '451134601338',
    'rdnm': '전라북도 전주시 덕진구 오송1길',
    'bldMnno': 15,
    'bldSlno': '',
    'bldMngNo': '4511312100101070143016691',
    'bldNm': '',
    'rdnmAdr': '전라북도 전주시 덕진구 오송1길 15',
    'oldZipcd': '561816',
    'newZipcd': '54823',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.128483752173,
    'lat': 35.8631606134181},
   {'bizesId': '10231561',
    'bizesNm': '피자앤닭컴',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41281',
    'signguNm': '고양시 덕양구',
    'adongCd': '4128160000',
    'adongNm': '관산동',
    'ldongCd': '4128111900',
    'ldongNm': '내유동',
    'lnoCd': '4128111900109030014',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 903,
    'lnoSlno': 14,
    'lnoAdr': '경기도 고양시 덕양구 내유동 903-14',
    'rdnmCd': '412814379207',
    'rdnm': '경기도 고양시 덕양구 통일로1267번길',
    'bldMnno': 12,
    'bldSlno': '',
    'bldMngNo': '4128111900109030014007802',
    'bldNm': '',
    'rdnmAdr': '경기도 고양시 덕양구 통일로1267번길 12',
    'oldZipcd': '412520',
    'newZipcd': '10262',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.842370394144,
    'lat': 37.7250861314577},
   {'bizesId': '10242205',
    'bizesNm': '하림치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48270',
    'signguNm': '밀양시',
    'adongCd': '4827034000',
    'adongNm': '산내면',
    'ldongCd': '4827034028',
    'ldongNm': '산내면',
    'lnoCd': '4827034028111160004',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1116,
    'lnoSlno': 4,
    'lnoAdr': '경상남도 밀양시 산내면 남명리 1116-4',
    'rdnmCd': '482703336029',
    'rdnm': '경상남도 밀양시 산내면 산내로',
    'bldMnno': 1134,
    'bldSlno': '',
    'bldMngNo': '4827034028111160004000237',
    'bldNm': '',
    'rdnmAdr': '경상남도 밀양시 산내면 산내로 1134',
    'oldZipcd': '627832',
    'newZipcd': '50415',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.952863807002,
    'lat': 35.5878569482513},
   {'bizesId': '10274423',
    'bizesNm': '핫썬치킨옥동점',
    'brchNm': '옥동점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '47',
    'ctprvnNm': '경상북도',
    'signguCd': '47170',
    'signguNm': '안동시',
    'adongCd': '4717065000',
    'adongNm': '옥동',
    'ldongCd': '4717013300',
    'ldongNm': '옥동',
    'lnoCd': '4717013300107870006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 787,
    'lnoSlno': 6,
    'lnoAdr': '경상북도 안동시 옥동 787-6',
    'rdnmCd': '471704721489',
    'rdnm': '경상북도 안동시 복주1길',
    'bldMnno': 92,
    'bldSlno': '',
    'bldMngNo': '4717013300107870006027092',
    'bldNm': '',
    'rdnmAdr': '경상북도 안동시 복주1길 92',
    'oldZipcd': '760310',
    'newZipcd': '36661',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.701658516225,
    'lat': 36.5633746443297},
   {'bizesId': '10398264',
    'bizesNm': 'BHC치킨',
    'brchNm': '강북점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42110',
    'signguNm': '춘천시',
    'adongCd': '4211070500',
    'adongNm': '신사우동',
    'ldongCd': '4211011900',
    'ldongNm': '사농동',
    'lnoCd': '4211011900100320003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 32,
    'lnoSlno': 3,
    'lnoAdr': '강원도 춘천시 사농동 32-3',
    'rdnmCd': '421104454187',
    'rdnm': '강원도 춘천시 마장길',
    'bldMnno': 62,
    'bldSlno': '',
    'bldMngNo': '4211011900100320003012141',
    'bldNm': '',
    'rdnmAdr': '강원도 춘천시 마장길 62',
    'oldZipcd': '200140',
    'newZipcd': '24221',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.730540190041,
    'lat': 37.9093809548376},
   {'bizesId': '10407416',
    'bizesNm': '치킨아이',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '29',
    'ctprvnNm': '광주광역시',
    'signguCd': '29170',
    'signguNm': '북구',
    'adongCd': '2917066900',
    'adongNm': '일곡동',
    'ldongCd': '2917012700',
    'ldongNm': '일곡동',
    'lnoCd': '2917012700108160003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 816,
    'lnoSlno': 3,
    'lnoAdr': '광주광역시 북구 일곡동 816-3',
    'rdnmCd': '291704286581',
    'rdnm': '광주광역시 북구 우치로537번길',
    'bldMnno': 10,
    'bldSlno': 1,
    'bldMngNo': '2917012700108160003015135',
    'bldNm': '동아아파트',
    'rdnmAdr': '광주광역시 북구 우치로537번길 10-1',
    'oldZipcd': '500795',
    'newZipcd': '61031',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.899570717972,
    'lat': 35.2126556214737},
   {'bizesId': '10423599',
    'bizesNm': '더화덕',
    'brchNm': '중동점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48121',
    'signguNm': '창원시 의창구',
    'adongCd': '4812151000',
    'adongNm': '의창동',
    'ldongCd': '4812110300',
    'ldongNm': '서상동',
    'lnoCd': '4812110300106680010',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 668,
    'lnoSlno': 10,
    'lnoAdr': '경상남도 창원시 의창구 서상동 668-10',
    'rdnmCd': '481214781529',
    'rdnm': '경상남도 창원시 의창구 의창대로254번길',
    'bldMnno': 19,
    'bldSlno': '',
    'bldMngNo': '4812110200103710009067614',
    'bldNm': '',
    'rdnmAdr': '경상남도 창원시 의창구 의창대로254번길 19',
    'oldZipcd': '641500',
    'newZipcd': '51370',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.625322165672,
    'lat': 35.2595259139192},
   {'bizesId': '10446382',
    'bizesNm': '월드양념통닭',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26380',
    'signguNm': '사하구',
    'adongCd': '2638058000',
    'adongNm': '장림1동',
    'ldongCd': '2638010500',
    'ldongNm': '장림동',
    'lnoCd': '2638010500106410130',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 641,
    'lnoSlno': 130,
    'lnoAdr': '부산광역시 사하구 장림동 641-130',
    'rdnmCd': '263804202433',
    'rdnm': '부산광역시 사하구 장림시장3길',
    'bldMnno': 80,
    'bldSlno': '',
    'bldMngNo': '2638010500106410130018701',
    'bldNm': '',
    'rdnmAdr': '부산광역시 사하구 장림시장3길 80',
    'oldZipcd': '604040',
    'newZipcd': '49476',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.967851385835,
    'lat': 35.0806599306185},
   {'bizesId': '10482089',
    'bizesNm': 'BBQ치킨',
    'brchNm': '진접센트레빌점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41360',
    'signguNm': '남양주시',
    'adongCd': '4136025300',
    'adongNm': '진접읍',
    'ldongCd': '4136025325',
    'ldongNm': '진접읍',
    'lnoCd': '4136025325107640000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 764,
    'lnoSlno': '',
    'lnoAdr': '경기도 남양주시 진접읍 부평리 764',
    'rdnmCd': '413603197029',
    'rdnm': '경기도 남양주시 진접읍 부평로',
    'bldMnno': 32,
    'bldSlno': '',
    'bldMngNo': '4136025325107640000000016',
    'bldNm': '진접센트레빌시티1단지상가',
    'rdnmAdr': '경기도 남양주시 진접읍 부평로 32',
    'oldZipcd': '472856',
    'newZipcd': '12022',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.200193095712,
    'lat': 37.7401667347414},
   {'bizesId': '10623611',
    'bizesNm': '치킨마루',
    'brchNm': '현대시장점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11620',
    'signguNm': '관악구',
    'adongCd': '1162060500',
    'adongNm': '은천동',
    'ldongCd': '1162010100',
    'ldongNm': '봉천동',
    'lnoCd': '1162010100117080000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1708,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 관악구 봉천동 1708',
    'rdnmCd': '116203005083',
    'rdnm': '서울특별시 관악구 봉천로',
    'bldMnno': 387,
    'bldSlno': '',
    'bldMngNo': '1162010100117080000040043',
    'bldNm': '두산아파트',
    'rdnmAdr': '서울특별시 관악구 봉천로 387',
    'oldZipcd': '151782',
    'newZipcd': '08750',
    'dongNo': '2',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.9427601496,
    'lat': 37.484309081691},
   {'bizesId': '10663586',
    'bizesNm': '교촌치킨',
    'brchNm': '신개금점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26230',
    'signguNm': '부산진구',
    'adongCd': '2623074000',

In [36]:
data[0]['header']

{'description': '소상공인시장진흥공단 주요상권내 상가업소정보',
 'columns': ['상가업소번호',
  '상호명',
  '지점명',
  '상권업종대분류코드',
  '상권업종대분류명',
  '상권업종중분류코드',
  '상권업종중분류명',
  '상권업종소분류코드',
  '상권업종소분류명',
  '표준산업분류코드',
  '표준산업분류명',
  '시도코드',
  '시도명',
  '시군구코드',
  '시군구명',
  '행정동코드',
  '행정동명',
  '법정동코드',
  '법정동명',
  'PNU코드',
  '대지구분코드',
  '대지구분명',
  '지번본번지',
  '지번부번지',
  '지번주소',
  '도로명코드',
  '도로명',
  '건물본번지',
  '건물부번지',
  '건물관리번호',
  '건물명',
  '도로명주소',
  '구우편번호',
  '신우편번호',
  '동정보',
  '층정보',
  '호정보',
  '경도',
  '위도'],
 'stdrYm': '202206',
 'resultCode': '00',
 'resultMsg': 'NORMAL SERVICE'}

In [18]:
data[0]['header']['columns']

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 'PNU코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

In [38]:
data[0]['body']

{'items': [{'bizesId': '10027626',
   'bizesNm': '장모님치킨가창점',
   'brchNm': '가창점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '27',
   'ctprvnNm': '대구광역시',
   'signguCd': '27710',
   'signguNm': '달성군',
   'adongCd': '2771031000',
   'adongNm': '가창면',
   'ldongCd': '2771031024',
   'ldongNm': '가창면',
   'lnoCd': '2771031024101200001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 120,
   'lnoSlno': 1,
   'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
   'rdnmCd': '277103148001',
   'rdnm': '대구광역시 달성군 가창면 가창동로',
   'bldMnno': 6,
   'bldSlno': '',
   'bldMngNo': '2771031024101200004036858',
   'bldNm': '',
   'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
   'oldZipcd': '711861',
   'newZipcd': '42938',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 128.644458591419,
   'lat': 35.7826625402814},
  {'bizesId': '10098244',
   'bizesNm': '짱구피자치킨',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41250',
   'signguNm': '동두천시',
   'adongCd': '4125056500',
   'adongNm': '불현동',
   'ldongCd': '4125010300',
   'ldongNm': '생연동',
   'lnoCd': '4125010300102680011',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 268,
   'lnoSlno': 11,
   'lnoAdr': '경기도 동두천시 생연동 268-11',
   'rdnmCd': '412503189006',
   'rdnm': '경기도 동두천시 못골로',
   'bldMnno': 30,
   'bldSlno': '',
   'bldMngNo': '4125010300102680011008557',
   'bldNm': '',
   'rdnmAdr': '경기도 동두천시 못골로 30',
   'oldZipcd': '483030',
   'newZipcd': '11320',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 127.06590346074,
   'lat': 37.9012616518346},
  {'bizesId': '10099459',
   'bizesNm': '쭈노치킨',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41570',
   'signguNm': '김포시',
   'adongCd': '4157025300',
   'adongNm': '고촌읍',
   'ldongCd': '4157025324',
   'ldongNm': '고촌읍',
   'lnoCd': '4157025324105380008',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 538,
   'lnoSlno': 8,
   'lnoAdr': '경기도 김포시 고촌읍 신곡리 538-8',
   'rdnmCd': '415704427512',
   'rdnm': '경기도 김포시 고촌읍 장차로13번길',
   'bldMnno': 18,
   'bldSlno': '',
   'bldMngNo': '4157025324105380008019970',
   'bldNm': '',
   'rdnmAdr': '경기도 김포시 고촌읍 장차로13번길 18',
   'oldZipcd': '415811',
   'newZipcd': '10126',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 126.769859060814,
   'lat': 37.6037515030602},
  {'bizesId': '10136167',
   'bizesNm': '치킨뱅이',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '42',
   'ctprvnNm': '강원도',
   'signguCd': '42130',
   'signguNm': '원주시',
   'adongCd': '4213059000',
   'adongNm': '단계동',
   'ldongCd': '4213011000',
   'ldongNm': '단계동',
   'lnoCd': '4213011000108300006',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 830,
   'lnoSlno': 6,
   'lnoAdr': '강원도 원주시 단계동 830-6',
   'rdnmCd': '421304457083',
   'rdnm': '강원도 원주시 금불3길',
   'bldMnno': 5,
   'bldSlno': '',
   'bldMngNo': '4213011000108300006022278',
   'bldNm': '',
   'rdnmAdr': '강원도 원주시 금불3길 5',
   'oldZipcd': '220938',
   'newZipcd': '26423',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.932025388709,
   'lat': 37.3483579547022},
  {'bizesId': '10136346',
   'bizesNm': '치킨월드율량점',
   'brchNm': '율량점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '43',
   'ctprvnNm': '충청북도',
   'signguCd': '43114',
   'signguNm': '청주시 청원구',
   'adongCd': '4311454000',
   'adongNm': '율량.사천동',
   'ldongCd': '4311410300',
   'ldongNm': '율량동',
   'lnoCd': '4311410300108060000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 806,
   'lnoSlno': '',
   'lnoAdr': '충청북도 청주시 청원구 율량동 806',
   'rdnmCd': '431144508043',
   'rdnm': '충청북도 청주시 청원구 공항로138번길',
   'bldMnno': 53,
   'bldSlno': '',
   'bldMngNo': '4311111500108060000045239',
   'bldNm': '',
   'rdnmAdr': '충청북도 청주시 청원구 공항로138번길 53',
   'oldZipcd': '363818',
   'newZipcd': '28328',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.487585541514,
   'lat': 36.6698161542425},
  {'bizesId': '10150151',
   'bizesNm': 'KFC',
   'brchNm': '수원이마트점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41113',
   'signguNm': '수원시 권선구',
   'adongCd': '4111368000',
   'adongNm': '권선2동',
   'ldongCd': '4111313700',
   'ldongNm': '권선동',
   'lnoCd': '4111313700111890000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1189,
   'lnoSlno': '',
   'lnoAdr': '경기도 수원시 권선구 권선동 1189',
   'rdnmCd': '411132012008',
   'rdnm': '경기도 수원시 권선구 경수대로',
   'bldMnno': 270,
   'bldSlno': '',
   'bldMngNo': '4111313700111890000027851',
   'bldNm': '할인점동',
   'rdnmAdr': '경기도 수원시 권선구 경수대로 270',
   'oldZipcd': '441713',
   'newZipcd': '16585',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.020087664145,
   'lat': 37.2501017782401},
  {'bizesId': '10186527',
   'bizesNm': '토마토두마리치킨',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11440',
   'signguNm': '마포구',
   'adongCd': '1144063000',
   'adongNm': '신수동',
   'ldongCd': '1144011300',
   'ldongNm': '구수동',
   'lnoCd': '1144011300100700001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 70,
   'lnoSlno': 1,
   'lnoAdr': '서울특별시 마포구 구수동 70-1',
   'rdnmCd': '114403113023',
   'rdnm': '서울특별시 마포구 토정로',
   'bldMnno': 195,
   'bldSlno': 1,
   'bldMngNo': '1144011300100700001008546',
   'bldNm': '정우빌딩',
   'rdnmAdr': '서울특별시 마포구 토정로 195-1',
   'oldZipcd': '121130',
   'newZipcd': '04087',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 126.932820696234,
   'lat': 37.545508849345},
  {'bizesId': '10208331',
   'bizesNm': '페리카나치킨연수우성체인점',
   'brchNm': '연수우성체인점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '28',
   'ctprvnNm': '인천광역시',
   'signguCd': '28185',
   'signguNm': '연수구',
   'adongCd': '2818576200',
   'adongNm': '연수2동',
   'ldongCd': '2818510300',
   'ldongNm': '연수동',
   'lnoCd': '2818510300106340000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 634,
   'lnoSlno': '',
   'lnoAdr': '인천광역시 연수구 연수동 634',
   'rdnmCd': '281853152021',
   'rdnm': '인천광역시 연수구 원인재로',
   'bldMnno': 180,
   'bldSlno': '',
   'bldMngNo': '2818510300106340000007257',
   'bldNm': '연수우성2차아파트',
   'rdnmAdr': '인천광역시 연수구 원인재로 180',
   'oldZipcd': '406765',
   'newZipcd': '21931',
   'dongNo': '',
   'flrNo': '2',
   'hoNo': '',
   'lon': 126.683928104747,
   'lat': 37.4122665635834},
  {'bizesId': '10208355',
   'bizesNm': '페리카나치킨벽산분점',
   'brchNm': '벽산분점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '42',
   'ctprvnNm': '강원도',
   'signguCd': '42130',
   'signguNm': '원주시',
   'adongCd': '4213059000',
   'adongNm': '단계동',
   'ldongCd': '4213011000',
   'ldongNm': '단계동',
   'lnoCd': '4213011000108130012',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 813,
   'lnoSlno': 12,
   'lnoAdr': '강원도 원주시 단계동 813-12',
   'rdnmCd': '421304457083',
   'rdnm': '강원도 원주시 금불3길',
   'bldMnno': 34,
   'bldSlno': '',
   'bldMngNo': '4213011000108130012022273',
   'bldNm': '',
   'rdnmAdr': '강원도 원주시 금불3길 34',
   'oldZipcd': '220938',
   'newZipcd': '26423',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 127.93187697793,
   'lat': 37.3502141596654},
  {'bizesId': '10208360',
   'bizesNm': '페리카나치킨',
   'brchNm': '송천점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '45',
   'ctprvnNm': '전라북도',
   'signguCd': '45113',
   'signguNm': '전주시 덕진구',
   'adongCd': '4511364100',
   'adongNm': '송천1동',
   'ldongCd': '4511312100',
   'ldongNm': '송천동1가',
   'lnoCd': '4511312100101070143',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 107,
   'lnoSlno': 143,
   'lnoAdr': '전라북도 전주시 덕진구 송천동1가 107-143',
   'rdnmCd': '451134601338',
   'rdnm': '전라북도 전주시 덕진구 오송1길',
   'bldMnno': 15,
   'bldSlno': '',
   'bldMngNo': '4511312100101070143016691',
   'bldNm': '',
   'rdnmAdr': '전라북도 전주시 덕진구 오송1길 15',
   'oldZipcd': '561816',
   'newZipcd': '54823',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 127.128483752173,
   'lat': 35.8631606134181},
  {'bizesId': '10231561',
   'bizesNm': '피자앤닭컴',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41281',
   'signguNm': '고양시 덕양구',
   'adongCd': '4128160000',
   'adongNm': '관산동',
   'ldongCd': '4128111900',
   'ldongNm': '내유동',
   'lnoCd': '4128111900109030014',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 903,
   'lnoSlno': 14,
   'lnoAdr': '경기도 고양시 덕양구 내유동 903-14',
   'rdnmCd': '412814379207',
   'rdnm': '경기도 고양시 덕양구 통일로1267번길',
   'bldMnno': 12,
   'bldSlno': '',
   'bldMngNo': '4128111900109030014007802',
   'bldNm': '',
   'rdnmAdr': '경기도 고양시 덕양구 통일로1267번길 12',
   'oldZipcd': '412520',
   'newZipcd': '10262',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.842370394144,
   'lat': 37.7250861314577},
  {'bizesId': '10242205',
   'bizesNm': '하림치킨',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '48',
   'ctprvnNm': '경상남도',
   'signguCd': '48270',
   'signguNm': '밀양시',
   'adongCd': '4827034000',
   'adongNm': '산내면',
   'ldongCd': '4827034028',
   'ldongNm': '산내면',
   'lnoCd': '4827034028111160004',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1116,
   'lnoSlno': 4,
   'lnoAdr': '경상남도 밀양시 산내면 남명리 1116-4',
   'rdnmCd': '482703336029',
   'rdnm': '경상남도 밀양시 산내면 산내로',
   'bldMnno': 1134,
   'bldSlno': '',
   'bldMngNo': '4827034028111160004000237',
   'bldNm': '',
   'rdnmAdr': '경상남도 밀양시 산내면 산내로 1134',
   'oldZipcd': '627832',
   'newZipcd': '50415',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 128.952863807002,
   'lat': 35.5878569482513},
  {'bizesId': '10274423',
   'bizesNm': '핫썬치킨옥동점',
   'brchNm': '옥동점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '47',
   'ctprvnNm': '경상북도',
   'signguCd': '47170',
   'signguNm': '안동시',
   'adongCd': '4717065000',
   'adongNm': '옥동',
   'ldongCd': '4717013300',
   'ldongNm': '옥동',
   'lnoCd': '4717013300107870006',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 787,
   'lnoSlno': 6,
   'lnoAdr': '경상북도 안동시 옥동 787-6',
   'rdnmCd': '471704721489',
   'rdnm': '경상북도 안동시 복주1길',
   'bldMnno': 92,
   'bldSlno': '',
   'bldMngNo': '4717013300107870006027092',
   'bldNm': '',
   'rdnmAdr': '경상북도 안동시 복주1길 92',
   'oldZipcd': '760310',
   'newZipcd': '36661',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 128.701658516225,
   'lat': 36.5633746443297},
  {'bizesId': '10398264',
   'bizesNm': 'BHC치킨',
   'brchNm': '강북점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '42',
   'ctprvnNm': '강원도',
   'signguCd': '42110',
   'signguNm': '춘천시',
   'adongCd': '4211070500',
   'adongNm': '신사우동',
   'ldongCd': '4211011900',
   'ldongNm': '사농동',
   'lnoCd': '4211011900100320003',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 32,
   'lnoSlno': 3,
   'lnoAdr': '강원도 춘천시 사농동 32-3',
   'rdnmCd': '421104454187',
   'rdnm': '강원도 춘천시 마장길',
   'bldMnno': 62,
   'bldSlno': '',
   'bldMngNo': '4211011900100320003012141',
   'bldNm': '',
   'rdnmAdr': '강원도 춘천시 마장길 62',
   'oldZipcd': '200140',
   'newZipcd': '24221',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 127.730540190041,
   'lat': 37.9093809548376},
  {'bizesId': '10407416',
   'bizesNm': '치킨아이',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '29',
   'ctprvnNm': '광주광역시',
   'signguCd': '29170',
   'signguNm': '북구',
   'adongCd': '2917066900',
   'adongNm': '일곡동',
   'ldongCd': '2917012700',
   'ldongNm': '일곡동',
   'lnoCd': '2917012700108160003',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 816,
   'lnoSlno': 3,
   'lnoAdr': '광주광역시 북구 일곡동 816-3',
   'rdnmCd': '291704286581',
   'rdnm': '광주광역시 북구 우치로537번길',
   'bldMnno': 10,
   'bldSlno': 1,
   'bldMngNo': '2917012700108160003015135',
   'bldNm': '동아아파트',
   'rdnmAdr': '광주광역시 북구 우치로537번길 10-1',
   'oldZipcd': '500795',
   'newZipcd': '61031',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.899570717972,
   'lat': 35.2126556214737},
  {'bizesId': '10423599',
   'bizesNm': '더화덕',
   'brchNm': '중동점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '48',
   'ctprvnNm': '경상남도',
   'signguCd': '48121',
   'signguNm': '창원시 의창구',
   'adongCd': '4812151000',
   'adongNm': '의창동',
   'ldongCd': '4812110300',
   'ldongNm': '서상동',
   'lnoCd': '4812110300106680010',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 668,
   'lnoSlno': 10,
   'lnoAdr': '경상남도 창원시 의창구 서상동 668-10',
   'rdnmCd': '481214781529',
   'rdnm': '경상남도 창원시 의창구 의창대로254번길',
   'bldMnno': 19,
   'bldSlno': '',
   'bldMngNo': '4812110200103710009067614',
   'bldNm': '',
   'rdnmAdr': '경상남도 창원시 의창구 의창대로254번길 19',
   'oldZipcd': '641500',
   'newZipcd': '51370',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 128.625322165672,
   'lat': 35.2595259139192},
  {'bizesId': '10446382',
   'bizesNm': '월드양념통닭',
   'brchNm': '',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '26',
   'ctprvnNm': '부산광역시',
   'signguCd': '26380',
   'signguNm': '사하구',
   'adongCd': '2638058000',
   'adongNm': '장림1동',
   'ldongCd': '2638010500',
   'ldongNm': '장림동',
   'lnoCd': '2638010500106410130',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 641,
   'lnoSlno': 130,
   'lnoAdr': '부산광역시 사하구 장림동 641-130',
   'rdnmCd': '263804202433',
   'rdnm': '부산광역시 사하구 장림시장3길',
   'bldMnno': 80,
   'bldSlno': '',
   'bldMngNo': '2638010500106410130018701',
   'bldNm': '',
   'rdnmAdr': '부산광역시 사하구 장림시장3길 80',
   'oldZipcd': '604040',
   'newZipcd': '49476',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 128.967851385835,
   'lat': 35.0806599306185},
  {'bizesId': '10482089',
   'bizesNm': 'BBQ치킨',
   'brchNm': '진접센트레빌점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '41',
   'ctprvnNm': '경기도',
   'signguCd': '41360',
   'signguNm': '남양주시',
   'adongCd': '4136025300',
   'adongNm': '진접읍',
   'ldongCd': '4136025325',
   'ldongNm': '진접읍',
   'lnoCd': '4136025325107640000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 764,
   'lnoSlno': '',
   'lnoAdr': '경기도 남양주시 진접읍 부평리 764',
   'rdnmCd': '413603197029',
   'rdnm': '경기도 남양주시 진접읍 부평로',
   'bldMnno': 32,
   'bldSlno': '',
   'bldMngNo': '4136025325107640000000016',
   'bldNm': '진접센트레빌시티1단지상가',
   'rdnmAdr': '경기도 남양주시 진접읍 부평로 32',
   'oldZipcd': '472856',
   'newZipcd': '12022',
   'dongNo': '',
   'flrNo': '',
   'hoNo': '',
   'lon': 127.200193095712,
   'lat': 37.7401667347414},
  {'bizesId': '10623611',
   'bizesNm': '치킨마루',
   'brchNm': '현대시장점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '11',
   'ctprvnNm': '서울특별시',
   'signguCd': '11620',
   'signguNm': '관악구',
   'adongCd': '1162060500',
   'adongNm': '은천동',
   'ldongCd': '1162010100',
   'ldongNm': '봉천동',
   'lnoCd': '1162010100117080000',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 1708,
   'lnoSlno': '',
   'lnoAdr': '서울특별시 관악구 봉천동 1708',
   'rdnmCd': '116203005083',
   'rdnm': '서울특별시 관악구 봉천로',
   'bldMnno': 387,
   'bldSlno': '',
   'bldMngNo': '1162010100117080000040043',
   'bldNm': '두산아파트',
   'rdnmAdr': '서울특별시 관악구 봉천로 387',
   'oldZipcd': '151782',
   'newZipcd': '08750',
   'dongNo': '2',
   'flrNo': '',
   'hoNo': '',
   'lon': 126.9427601496,
   'lat': 37.484309081691},
  {'bizesId': '10663586',
   'bizesNm': '교촌치킨',
   'brchNm': '신개금점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '26',
   'ctprvnNm': '부산광역시',
   'signguCd': '26230',
   'signguNm': '부산진구',
   'adongCd': '2623074000',
   'adongNm': '개금1동',
   'ldongCd': '2623011100',
   'ldongNm': '개금동',
   'lnoCd': '2623011100102010006',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 201,
   'lnoSlno': 6,
   'lnoAdr': '부산광역시 부산진구 개금동 201-6',
   'rdnmCd': '262302006015',
   'rdnm': '부산광역시 부산진구 가야대로',
   'bldMnno': 475,
   'bldSlno': '',
   'bldMngNo': '2623011100102010037024141',
   'bldNm': '',
   'rdnmAdr': '부산광역시 부산진구 가야대로 475',
   'oldZipcd': '614110',
   'newZipcd': '47268',
   'dongNo': '',
   'flrNo': '1',
   'hoNo': '',
   'lon': 129.024050678641,
   'lat': 35.1534913537491},
  {'bizesId': '10797221',
   'bizesNm': '새때치킨대산점',
   'brchNm': '대산점',
   'indsLclsCd': 'Q',
   'indsLclsNm': '음식',
   'indsMclsCd': 'Q05',
   'indsMclsNm': '닭/오리요리',
   'indsSclsCd': 'Q05A08',
   'indsSclsNm': '후라이드/양념치킨',
   'ksicCd': 'I56193',
   'ksicNm': '치킨 전문점',
   'ctprvnCd': '48',
   'ctprvnNm': '경상남도',
   'signguCd': '48121',
   'signguNm': '창원시 의창구',
   'adongCd': '4812132000',
   'adongNm': '대산면',
   'ldongCd': '4812132024',
   'ldongNm': '대산면',
   'lnoCd': '4812132024103800001',
   'plotSctCd': '1',
   'plotSctNm': '대지',
   'lnoMnno': 380,
   'lnoSlno': 1,
   'lnoAdr': '경상남도 창원시 의창구 대산면 가술리 380-1',
   'rdnmCd': '481214781001',
   'rdnm': '경상남도 창원시 의창구 대산면 가술길',
   'bldMnno': 5,
   'bldSlno': 8,
   'bldMngNo': '4812132024103800001037798',
   'bldNm': '',

In [41]:
data[0]['body']['items'][0]

{'bizesId': '10027626',
 'bizesNm': '장모님치킨가창점',
 'brchNm': '가창점',
 'indsLclsCd': 'Q',
 'indsLclsNm': '음식',
 'indsMclsCd': 'Q05',
 'indsMclsNm': '닭/오리요리',
 'indsSclsCd': 'Q05A08',
 'indsSclsNm': '후라이드/양념치킨',
 'ksicCd': 'I56193',
 'ksicNm': '치킨 전문점',
 'ctprvnCd': '27',
 'ctprvnNm': '대구광역시',
 'signguCd': '27710',
 'signguNm': '달성군',
 'adongCd': '2771031000',
 'adongNm': '가창면',
 'ldongCd': '2771031024',
 'ldongNm': '가창면',
 'lnoCd': '2771031024101200001',
 'plotSctCd': '1',
 'plotSctNm': '대지',
 'lnoMnno': 120,
 'lnoSlno': 1,
 'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
 'rdnmCd': '277103148001',
 'rdnm': '대구광역시 달성군 가창면 가창동로',
 'bldMnno': 6,
 'bldSlno': '',
 'bldMngNo': '2771031024101200004036858',
 'bldNm': '',
 'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
 'oldZipcd': '711861',
 'newZipcd': '42938',
 'dongNo': '',
 'flrNo': '1',
 'hoNo': '',
 'lon': 128.644458591419,
 'lat': 35.7826625402814}

In [42]:
data[0].keys()

dict_keys(['header', 'body'])

In [44]:
data[0]['body']['items'][0].values()

dict_values(['10027626', '장모님치킨가창점', '가창점', 'Q', '음식', 'Q05', '닭/오리요리', 'Q05A08', '후라이드/양념치킨', 'I56193', '치킨 전문점', '27', '대구광역시', '27710', '달성군', '2771031000', '가창면', '2771031024', '가창면', '2771031024101200001', '1', '대지', 120, 1, '대구광역시 달성군 가창면 냉천리 120-1', '277103148001', '대구광역시 달성군 가창면 가창동로', 6, '', '2771031024101200004036858', '', '대구광역시 달성군 가창면 가창동로 6', '711861', '42938', '', '1', '', 128.644458591419, 35.7826625402814])

In [37]:
for i in data[0]['header']['columns']:
    data_list = []
    print(i)

    #     for item in chick[0]['body']['items'][:2]:
#         chick_list.append(item[i])
#         print(i, chick_list)

상가업소번호
상호명
지점명
상권업종대분류코드
상권업종대분류명
상권업종중분류코드
상권업종중분류명
상권업종소분류코드
상권업종소분류명
표준산업분류코드
표준산업분류명
시도코드
시도명
시군구코드
시군구명
행정동코드
행정동명
법정동코드
법정동명
PNU코드
대지구분코드
대지구분명
지번본번지
지번부번지
지번주소
도로명코드
도로명
건물본번지
건물부번지
건물관리번호
건물명
도로명주소
구우편번호
신우편번호
동정보
층정보
호정보
경도
위도

In [46]:
chick[0]['body']['items'][:2]

[{'bizesId': '10027626',
  'bizesNm': '장모님치킨가창점',
  'brchNm': '가창점',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '27',
  'ctprvnNm': '대구광역시',
  'signguCd': '27710',
  'signguNm': '달성군',
  'adongCd': '2771031000',
  'adongNm': '가창면',
  'ldongCd': '2771031024',
  'ldongNm': '가창면',
  'lnoCd': '2771031024101200001',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 120,
  'lnoSlno': 1,
  'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
  'rdnmCd': '277103148001',
  'rdnm': '대구광역시 달성군 가창면 가창동로',
  'bldMnno': 6,
  'bldSlno': '',
  'bldMngNo': '2771031024101200004036858',
  'bldNm': '',
  'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
  'oldZipcd': '711861',
  'newZipcd': '42938',
  'dongNo': '',
  'flrNo': '1',
  'hoNo': '',
  'lon': 128.644458591419,
  'lat': 35.7826625402814},
 {'bizesId': '10098244',
  'bizesNm': '짱구피자치킨',
  'brchNm': '',
  'indsLclsCd': 'Q',
  'indsLclsNm': '음식',
  'indsMclsCd': 'Q05',
  'indsMclsNm': '닭/오리요리',
  'indsSclsCd': 'Q05A08',
  'indsSclsNm': '후라이드/양념치킨',
  'ksicCd': 'I56193',
  'ksicNm': '치킨 전문점',
  'ctprvnCd': '41',
  'ctprvnNm': '경기도',
  'signguCd': '41250',
  'signguNm': '동두천시',
  'adongCd': '4125056500',
  'adongNm': '불현동',
  'ldongCd': '4125010300',
  'ldongNm': '생연동',
  'lnoCd': '4125010300102680011',
  'plotSctCd': '1',
  'plotSctNm': '대지',
  'lnoMnno': 268,
  'lnoSlno': 11,
  'lnoAdr': '경기도 동두천시 생연동 268-11',
  'rdnmCd': '412503189006',
  'rdnm': '경기도 동두천시 못골로',
  'bldMnno': 30,
  'bldSlno': '',
  'bldMngNo': '4125010300102680011008557',
  'bldNm': '',
  'rdnmAdr': '경기도 동두천시 못골로 30',
  'oldZipcd': '483030',
  'newZipcd': '11320',
  'dongNo': '',
  'flrNo': '',
  'hoNo': '',
  'lon': 127.06590346074,
  'lat': 37.9012616518346}]

In [17]:
# 풀이
result3 = {}
for item in chick[0]['body']['items']:
        for key, value in item.items():
            result3.setdefault(key, []).append(value)
len(result3['bizesId'])

1000

In [48]:
result3 = {}

for key in chick[0]['header']['columns']:
    chick_list = []
    for item in chick[0]['body']['items'][:2]:
        print(item)
        chick_list.append(item[key])
    print(key, chick_list)
    result3[key] = chick_list

{'bizesId': '10027626', 'bizesNm': '장모님치킨가창점', 'brchNm': '가창점', 'indsLclsCd': 'Q', 'indsLclsNm': '음식', 'indsMclsCd': 'Q05', 'indsMclsNm': '닭/오리요리', 'indsSclsCd': 'Q05A08', 'indsSclsNm': '후라이드/양념치킨', 'ksicCd': 'I56193', 'ksicNm': '치킨 전문점', 'ctprvnCd': '27', 'ctprvnNm': '대구광역시', 'signguCd': '27710', 'signguNm': '달성군', 'adongCd': '2771031000', 'adongNm': '가창면', 'ldongCd': '2771031024', 'ldongNm': '가창면', 'lnoCd': '2771031024101200001', 'plotSctCd': '1', 'plotSctNm': '대지', 'lnoMnno': 120, 'lnoSlno': 1, 'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1', 'rdnmCd': '277103148001', 'rdnm': '대구광역시 달성군 가창면 가창동로', 'bldMnno': 6, 'bldSlno': '', 'bldMngNo': '2771031024101200004036858', 'bldNm': '', 'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6', 'oldZipcd': '711861', 'newZipcd': '42938', 'dongNo': '', 'flrNo': '1', 'hoNo': '', 'lon': 128.644458591419, 'lat': 35.7826625402814}

KeyError: '상가업소번호'

In [7]:
result3[key]

[{'items': [{'bizesId': '10027626',
    'bizesNm': '장모님치킨가창점',
    'brchNm': '가창점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '27',
    'ctprvnNm': '대구광역시',
    'signguCd': '27710',
    'signguNm': '달성군',
    'adongCd': '2771031000',
    'adongNm': '가창면',
    'ldongCd': '2771031024',
    'ldongNm': '가창면',
    'lnoCd': '2771031024101200001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 120,
    'lnoSlno': 1,
    'lnoAdr': '대구광역시 달성군 가창면 냉천리 120-1',
    'rdnmCd': '277103148001',
    'rdnm': '대구광역시 달성군 가창면 가창동로',
    'bldMnno': 6,
    'bldSlno': '',
    'bldMngNo': '2771031024101200004036858',
    'bldNm': '',
    'rdnmAdr': '대구광역시 달성군 가창면 가창동로 6',
    'oldZipcd': '711861',
    'newZipcd': '42938',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.644458591419,
    'lat': 35.7826625402814},
   {'bizesId': '10098244',
    'bizesNm': '짱구피자치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41250',
    'signguNm': '동두천시',
    'adongCd': '4125056500',
    'adongNm': '불현동',
    'ldongCd': '4125010300',
    'ldongNm': '생연동',
    'lnoCd': '4125010300102680011',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 268,
    'lnoSlno': 11,
    'lnoAdr': '경기도 동두천시 생연동 268-11',
    'rdnmCd': '412503189006',
    'rdnm': '경기도 동두천시 못골로',
    'bldMnno': 30,
    'bldSlno': '',
    'bldMngNo': '4125010300102680011008557',
    'bldNm': '',
    'rdnmAdr': '경기도 동두천시 못골로 30',
    'oldZipcd': '483030',
    'newZipcd': '11320',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.06590346074,
    'lat': 37.9012616518346},
   {'bizesId': '10099459',
    'bizesNm': '쭈노치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41570',
    'signguNm': '김포시',
    'adongCd': '4157025300',
    'adongNm': '고촌읍',
    'ldongCd': '4157025324',
    'ldongNm': '고촌읍',
    'lnoCd': '4157025324105380008',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 538,
    'lnoSlno': 8,
    'lnoAdr': '경기도 김포시 고촌읍 신곡리 538-8',
    'rdnmCd': '415704427512',
    'rdnm': '경기도 김포시 고촌읍 장차로13번길',
    'bldMnno': 18,
    'bldSlno': '',
    'bldMngNo': '4157025324105380008019970',
    'bldNm': '',
    'rdnmAdr': '경기도 김포시 고촌읍 장차로13번길 18',
    'oldZipcd': '415811',
    'newZipcd': '10126',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.769859060814,
    'lat': 37.6037515030602},
   {'bizesId': '10136167',
    'bizesNm': '치킨뱅이',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42130',
    'signguNm': '원주시',
    'adongCd': '4213059000',
    'adongNm': '단계동',
    'ldongCd': '4213011000',
    'ldongNm': '단계동',
    'lnoCd': '4213011000108300006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 830,
    'lnoSlno': 6,
    'lnoAdr': '강원도 원주시 단계동 830-6',
    'rdnmCd': '421304457083',
    'rdnm': '강원도 원주시 금불3길',
    'bldMnno': 5,
    'bldSlno': '',
    'bldMngNo': '4213011000108300006022278',
    'bldNm': '',
    'rdnmAdr': '강원도 원주시 금불3길 5',
    'oldZipcd': '220938',
    'newZipcd': '26423',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.932025388709,
    'lat': 37.3483579547022},
   {'bizesId': '10136346',
    'bizesNm': '치킨월드율량점',
    'brchNm': '율량점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '43',
    'ctprvnNm': '충청북도',
    'signguCd': '43114',
    'signguNm': '청주시 청원구',
    'adongCd': '4311454000',
    'adongNm': '율량.사천동',
    'ldongCd': '4311410300',
    'ldongNm': '율량동',
    'lnoCd': '4311410300108060000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 806,
    'lnoSlno': '',
    'lnoAdr': '충청북도 청주시 청원구 율량동 806',
    'rdnmCd': '431144508043',
    'rdnm': '충청북도 청주시 청원구 공항로138번길',
    'bldMnno': 53,
    'bldSlno': '',
    'bldMngNo': '4311111500108060000045239',
    'bldNm': '',
    'rdnmAdr': '충청북도 청주시 청원구 공항로138번길 53',
    'oldZipcd': '363818',
    'newZipcd': '28328',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.487585541514,
    'lat': 36.6698161542425},
   {'bizesId': '10150151',
    'bizesNm': 'KFC',
    'brchNm': '수원이마트점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41113',
    'signguNm': '수원시 권선구',
    'adongCd': '4111368000',
    'adongNm': '권선2동',
    'ldongCd': '4111313700',
    'ldongNm': '권선동',
    'lnoCd': '4111313700111890000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1189,
    'lnoSlno': '',
    'lnoAdr': '경기도 수원시 권선구 권선동 1189',
    'rdnmCd': '411132012008',
    'rdnm': '경기도 수원시 권선구 경수대로',
    'bldMnno': 270,
    'bldSlno': '',
    'bldMngNo': '4111313700111890000027851',
    'bldNm': '할인점동',
    'rdnmAdr': '경기도 수원시 권선구 경수대로 270',
    'oldZipcd': '441713',
    'newZipcd': '16585',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.020087664145,
    'lat': 37.2501017782401},
   {'bizesId': '10186527',
    'bizesNm': '토마토두마리치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11440',
    'signguNm': '마포구',
    'adongCd': '1144063000',
    'adongNm': '신수동',
    'ldongCd': '1144011300',
    'ldongNm': '구수동',
    'lnoCd': '1144011300100700001',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 70,
    'lnoSlno': 1,
    'lnoAdr': '서울특별시 마포구 구수동 70-1',
    'rdnmCd': '114403113023',
    'rdnm': '서울특별시 마포구 토정로',
    'bldMnno': 195,
    'bldSlno': 1,
    'bldMngNo': '1144011300100700001008546',
    'bldNm': '정우빌딩',
    'rdnmAdr': '서울특별시 마포구 토정로 195-1',
    'oldZipcd': '121130',
    'newZipcd': '04087',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 126.932820696234,
    'lat': 37.545508849345},
   {'bizesId': '10208331',
    'bizesNm': '페리카나치킨연수우성체인점',
    'brchNm': '연수우성체인점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '28',
    'ctprvnNm': '인천광역시',
    'signguCd': '28185',
    'signguNm': '연수구',
    'adongCd': '2818576200',
    'adongNm': '연수2동',
    'ldongCd': '2818510300',
    'ldongNm': '연수동',
    'lnoCd': '2818510300106340000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 634,
    'lnoSlno': '',
    'lnoAdr': '인천광역시 연수구 연수동 634',
    'rdnmCd': '281853152021',
    'rdnm': '인천광역시 연수구 원인재로',
    'bldMnno': 180,
    'bldSlno': '',
    'bldMngNo': '2818510300106340000007257',
    'bldNm': '연수우성2차아파트',
    'rdnmAdr': '인천광역시 연수구 원인재로 180',
    'oldZipcd': '406765',
    'newZipcd': '21931',
    'dongNo': '',
    'flrNo': '2',
    'hoNo': '',
    'lon': 126.683928104747,
    'lat': 37.4122665635834},
   {'bizesId': '10208355',
    'bizesNm': '페리카나치킨벽산분점',
    'brchNm': '벽산분점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42130',
    'signguNm': '원주시',
    'adongCd': '4213059000',
    'adongNm': '단계동',
    'ldongCd': '4213011000',
    'ldongNm': '단계동',
    'lnoCd': '4213011000108130012',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 813,
    'lnoSlno': 12,
    'lnoAdr': '강원도 원주시 단계동 813-12',
    'rdnmCd': '421304457083',
    'rdnm': '강원도 원주시 금불3길',
    'bldMnno': 34,
    'bldSlno': '',
    'bldMngNo': '4213011000108130012022273',
    'bldNm': '',
    'rdnmAdr': '강원도 원주시 금불3길 34',
    'oldZipcd': '220938',
    'newZipcd': '26423',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 127.93187697793,
    'lat': 37.3502141596654},
   {'bizesId': '10208360',
    'bizesNm': '페리카나치킨',
    'brchNm': '송천점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '45',
    'ctprvnNm': '전라북도',
    'signguCd': '45113',
    'signguNm': '전주시 덕진구',
    'adongCd': '4511364100',
    'adongNm': '송천1동',
    'ldongCd': '4511312100',
    'ldongNm': '송천동1가',
    'lnoCd': '4511312100101070143',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 107,
    'lnoSlno': 143,
    'lnoAdr': '전라북도 전주시 덕진구 송천동1가 107-143',
    'rdnmCd': '451134601338',
    'rdnm': '전라북도 전주시 덕진구 오송1길',
    'bldMnno': 15,
    'bldSlno': '',
    'bldMngNo': '4511312100101070143016691',
    'bldNm': '',
    'rdnmAdr': '전라북도 전주시 덕진구 오송1길 15',
    'oldZipcd': '561816',
    'newZipcd': '54823',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.128483752173,
    'lat': 35.8631606134181},
   {'bizesId': '10231561',
    'bizesNm': '피자앤닭컴',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41281',
    'signguNm': '고양시 덕양구',
    'adongCd': '4128160000',
    'adongNm': '관산동',
    'ldongCd': '4128111900',
    'ldongNm': '내유동',
    'lnoCd': '4128111900109030014',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 903,
    'lnoSlno': 14,
    'lnoAdr': '경기도 고양시 덕양구 내유동 903-14',
    'rdnmCd': '412814379207',
    'rdnm': '경기도 고양시 덕양구 통일로1267번길',
    'bldMnno': 12,
    'bldSlno': '',
    'bldMngNo': '4128111900109030014007802',
    'bldNm': '',
    'rdnmAdr': '경기도 고양시 덕양구 통일로1267번길 12',
    'oldZipcd': '412520',
    'newZipcd': '10262',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.842370394144,
    'lat': 37.7250861314577},
   {'bizesId': '10242205',
    'bizesNm': '하림치킨',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48270',
    'signguNm': '밀양시',
    'adongCd': '4827034000',
    'adongNm': '산내면',
    'ldongCd': '4827034028',
    'ldongNm': '산내면',
    'lnoCd': '4827034028111160004',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1116,
    'lnoSlno': 4,
    'lnoAdr': '경상남도 밀양시 산내면 남명리 1116-4',
    'rdnmCd': '482703336029',
    'rdnm': '경상남도 밀양시 산내면 산내로',
    'bldMnno': 1134,
    'bldSlno': '',
    'bldMngNo': '4827034028111160004000237',
    'bldNm': '',
    'rdnmAdr': '경상남도 밀양시 산내면 산내로 1134',
    'oldZipcd': '627832',
    'newZipcd': '50415',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.952863807002,
    'lat': 35.5878569482513},
   {'bizesId': '10274423',
    'bizesNm': '핫썬치킨옥동점',
    'brchNm': '옥동점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '47',
    'ctprvnNm': '경상북도',
    'signguCd': '47170',
    'signguNm': '안동시',
    'adongCd': '4717065000',
    'adongNm': '옥동',
    'ldongCd': '4717013300',
    'ldongNm': '옥동',
    'lnoCd': '4717013300107870006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 787,
    'lnoSlno': 6,
    'lnoAdr': '경상북도 안동시 옥동 787-6',
    'rdnmCd': '471704721489',
    'rdnm': '경상북도 안동시 복주1길',
    'bldMnno': 92,
    'bldSlno': '',
    'bldMngNo': '4717013300107870006027092',
    'bldNm': '',
    'rdnmAdr': '경상북도 안동시 복주1길 92',
    'oldZipcd': '760310',
    'newZipcd': '36661',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 128.701658516225,
    'lat': 36.5633746443297},
   {'bizesId': '10398264',
    'bizesNm': 'BHC치킨',
    'brchNm': '강북점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '42',
    'ctprvnNm': '강원도',
    'signguCd': '42110',
    'signguNm': '춘천시',
    'adongCd': '4211070500',
    'adongNm': '신사우동',
    'ldongCd': '4211011900',
    'ldongNm': '사농동',
    'lnoCd': '4211011900100320003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 32,
    'lnoSlno': 3,
    'lnoAdr': '강원도 춘천시 사농동 32-3',
    'rdnmCd': '421104454187',
    'rdnm': '강원도 춘천시 마장길',
    'bldMnno': 62,
    'bldSlno': '',
    'bldMngNo': '4211011900100320003012141',
    'bldNm': '',
    'rdnmAdr': '강원도 춘천시 마장길 62',
    'oldZipcd': '200140',
    'newZipcd': '24221',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.730540190041,
    'lat': 37.9093809548376},
   {'bizesId': '10407416',
    'bizesNm': '치킨아이',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '29',
    'ctprvnNm': '광주광역시',
    'signguCd': '29170',
    'signguNm': '북구',
    'adongCd': '2917066900',
    'adongNm': '일곡동',
    'ldongCd': '2917012700',
    'ldongNm': '일곡동',
    'lnoCd': '2917012700108160003',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 816,
    'lnoSlno': 3,
    'lnoAdr': '광주광역시 북구 일곡동 816-3',
    'rdnmCd': '291704286581',
    'rdnm': '광주광역시 북구 우치로537번길',
    'bldMnno': 10,
    'bldSlno': 1,
    'bldMngNo': '2917012700108160003015135',
    'bldNm': '동아아파트',
    'rdnmAdr': '광주광역시 북구 우치로537번길 10-1',
    'oldZipcd': '500795',
    'newZipcd': '61031',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.899570717972,
    'lat': 35.2126556214737},
   {'bizesId': '10423599',
    'bizesNm': '더화덕',
    'brchNm': '중동점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '48',
    'ctprvnNm': '경상남도',
    'signguCd': '48121',
    'signguNm': '창원시 의창구',
    'adongCd': '4812151000',
    'adongNm': '의창동',
    'ldongCd': '4812110300',
    'ldongNm': '서상동',
    'lnoCd': '4812110300106680010',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 668,
    'lnoSlno': 10,
    'lnoAdr': '경상남도 창원시 의창구 서상동 668-10',
    'rdnmCd': '481214781529',
    'rdnm': '경상남도 창원시 의창구 의창대로254번길',
    'bldMnno': 19,
    'bldSlno': '',
    'bldMngNo': '4812110200103710009067614',
    'bldNm': '',
    'rdnmAdr': '경상남도 창원시 의창구 의창대로254번길 19',
    'oldZipcd': '641500',
    'newZipcd': '51370',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.625322165672,
    'lat': 35.2595259139192},
   {'bizesId': '10446382',
    'bizesNm': '월드양념통닭',
    'brchNm': '',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26380',
    'signguNm': '사하구',
    'adongCd': '2638058000',
    'adongNm': '장림1동',
    'ldongCd': '2638010500',
    'ldongNm': '장림동',
    'lnoCd': '2638010500106410130',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 641,
    'lnoSlno': 130,
    'lnoAdr': '부산광역시 사하구 장림동 641-130',
    'rdnmCd': '263804202433',
    'rdnm': '부산광역시 사하구 장림시장3길',
    'bldMnno': 80,
    'bldSlno': '',
    'bldMngNo': '2638010500106410130018701',
    'bldNm': '',
    'rdnmAdr': '부산광역시 사하구 장림시장3길 80',
    'oldZipcd': '604040',
    'newZipcd': '49476',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 128.967851385835,
    'lat': 35.0806599306185},
   {'bizesId': '10482089',
    'bizesNm': 'BBQ치킨',
    'brchNm': '진접센트레빌점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '41',
    'ctprvnNm': '경기도',
    'signguCd': '41360',
    'signguNm': '남양주시',
    'adongCd': '4136025300',
    'adongNm': '진접읍',
    'ldongCd': '4136025325',
    'ldongNm': '진접읍',
    'lnoCd': '4136025325107640000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 764,
    'lnoSlno': '',
    'lnoAdr': '경기도 남양주시 진접읍 부평리 764',
    'rdnmCd': '413603197029',
    'rdnm': '경기도 남양주시 진접읍 부평로',
    'bldMnno': 32,
    'bldSlno': '',
    'bldMngNo': '4136025325107640000000016',
    'bldNm': '진접센트레빌시티1단지상가',
    'rdnmAdr': '경기도 남양주시 진접읍 부평로 32',
    'oldZipcd': '472856',
    'newZipcd': '12022',
    'dongNo': '',
    'flrNo': '',
    'hoNo': '',
    'lon': 127.200193095712,
    'lat': 37.7401667347414},
   {'bizesId': '10623611',
    'bizesNm': '치킨마루',
    'brchNm': '현대시장점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '11',
    'ctprvnNm': '서울특별시',
    'signguCd': '11620',
    'signguNm': '관악구',
    'adongCd': '1162060500',
    'adongNm': '은천동',
    'ldongCd': '1162010100',
    'ldongNm': '봉천동',
    'lnoCd': '1162010100117080000',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 1708,
    'lnoSlno': '',
    'lnoAdr': '서울특별시 관악구 봉천동 1708',
    'rdnmCd': '116203005083',
    'rdnm': '서울특별시 관악구 봉천로',
    'bldMnno': 387,
    'bldSlno': '',
    'bldMngNo': '1162010100117080000040043',
    'bldNm': '두산아파트',
    'rdnmAdr': '서울특별시 관악구 봉천로 387',
    'oldZipcd': '151782',
    'newZipcd': '08750',
    'dongNo': '2',
    'flrNo': '',
    'hoNo': '',
    'lon': 126.9427601496,
    'lat': 37.484309081691},
   {'bizesId': '10663586',
    'bizesNm': '교촌치킨',
    'brchNm': '신개금점',
    'indsLclsCd': 'Q',
    'indsLclsNm': '음식',
    'indsMclsCd': 'Q05',
    'indsMclsNm': '닭/오리요리',
    'indsSclsCd': 'Q05A08',
    'indsSclsNm': '후라이드/양념치킨',
    'ksicCd': 'I56193',
    'ksicNm': '치킨 전문점',
    'ctprvnCd': '26',
    'ctprvnNm': '부산광역시',
    'signguCd': '26230',
    'signguNm': '부산진구',
    'adongCd': '2623074000',
    'adongNm': '개금1동',
    'ldongCd': '2623011100',
    'ldongNm': '개금동',
    'lnoCd': '2623011100102010006',
    'plotSctCd': '1',
    'plotSctNm': '대지',
    'lnoMnno': 201,
    'lnoSlno': 6,
    'lnoAdr': '부산광역시 부산진구 개금동 201-6',
    'rdnmCd': '262302006015',
    'rdnm': '부산광역시 부산진구 가야대로',
    'bldMnno': 475,
    'bldSlno': '',
    'bldMngNo': '2623011100102010037024141',
    'bldNm': '',
    'rdnmAdr': '부산광역시 부산진구 가야대로 475',
    'oldZipcd': '614110',
    'newZipcd': '47268',
    'dongNo': '',
    'flrNo': '1',
    'hoNo': '',
    'lon': 129.024050678641,
    'lat': 35.1534913537491},
   {'bizesId': '10797221',

In [8]:
result3_df = pd.DataFrame(result3)
result3_df

,header,body
0,"{'description': '소상공인시장진흥공단 주요상권내 상가업소정보', 'co...","{'items': [{'bizesId': '10027626', 'bizesNm': ..."
1,"{'description': '소상공인시장진흥공단 주요상권내 상가업소정보', 'co...","{'items': [{'bizesId': '11927910', 'bizesNm': ..."

* data에는 리스트 요소가 37개 있음.
* 리스트 요소 1개에는 1000개의 딕셔너리가 있고 그 안에 가게 정보가 있음
* 가게 정보는 body[0]['body']['items']에 있다.
* 가게 정보를 구성하는 key는 39개이다.

In [76]:
# chick[0]['body']['items'][0]

In [8]:
len(chick[0]['header']['columns'])

39

In [18]:
# 강사님 풀이

# len(chick[0]['body']['items'])

result3 = {}
for page in chick:
    for item in page['body']['items']:
        for key, value in item.items():
            result3.setdefault(key, []).append(value)
#         print(key, value)
len(result3['bizesId'])

36064

In [5]:
df = pd.DataFrame(result3)
df

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36995,11927120,두두두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4719034028104640013062144,,경상북도 구미시 해평면 강동로 1671,730873,39154,,1,,128.390989,36.199637
36996,11927310,호식이두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4272025029104520007040192,,강원도 홍천군 홍천읍 남산강변로 32,250930,25149,,1,,127.882012,37.685865
36997,11927491,또봉이치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2820010200100690027020930,,인천광역시 남동구 풀무로 9-2,405230,21510,,1,,126.709187,37.469419
36998,11927616,투마리치킨하늘도시점,하늘도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2811014600100330008000001,,인천광역시 중구 운중로 85-1,400811,22359,,1,,126.542880,37.493596
36999,11927757,노랑통닭,구리수택점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4131010500104480006008791,구리신성미소지움,경기도 구리시 이문안로 81,471030,11941,101,1,,127.140380,37.592408

In [13]:
chick[0]['header']['columns'][0]

'상가업소번호'

In [19]:
# key 이름을 header - column 한국어 이름으로 변경하기

result4 = {}
for page in chick:
    for item in chick[0]['body']['items']:
        for key, value in zip(page['header']['columns'], item.values()):
            result4.setdefault(key, []).append(value)
#         print(key, value)
df2 = pd.DataFrame(result4)
df2

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36995,11927120,두두두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4719034028104640013062144,,경상북도 구미시 해평면 강동로 1671,730873,39154,,1,,128.390989,36.199637
36996,11927310,호식이두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4272025029104520007040192,,강원도 홍천군 홍천읍 남산강변로 32,250930,25149,,1,,127.882012,37.685865
36997,11927491,또봉이치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2820010200100690027020930,,인천광역시 남동구 풀무로 9-2,405230,21510,,1,,126.709187,37.469419
36998,11927616,투마리치킨하늘도시점,하늘도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2811014600100330008000001,,인천광역시 중구 운중로 85-1,400811,22359,,1,,126.542880,37.493596
36999,11927757,노랑통닭,구리수택점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4131010500104480006008791,구리신성미소지움,경기도 구리시 이문안로 81,471030,11941,101,1,,127.140380,37.592408

# pandas의 json_normalize를 이용해서 DataFrame으로 만들기

제이슨 노말라이저는 리스트 안에 37개의 딕셔너리를 읽는다.<br>
header - descritption, colunmns 등<br>
body - items 등<br>
<br>
한 단계 더 내려가지 않음!

In [24]:
pd.json_normalize(chick)

,header.description,header.columns,header.stdrYm,header.resultCode,header.resultMsg,body.items,body.numOfRows,body.pageNo,body.totalCount
0,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '10027626', 'bizesNm': '장모님치킨가창점'...",1000,1,36064
1,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '11927910', 'bizesNm': '흥부네대박닭강정난...",1000,2,36064
2,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '12078226', 'bizesNm': '한국통닭', 'b...",1000,3,36064
3,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '12448225', 'bizesNm': 'BHC치킨', '...",1000,4,36064
4,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '12601898', 'bizesNm': '굽네치킨서림점',...",1000,5,36064
5,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '15841722', 'bizesNm': '카카오닭', 'b...",1000,6,36064
6,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '16099079', 'bizesNm': '지코바양념치킨',...",1000,7,36064
7,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '16280562', 'bizesNm': '지코바치킨', '...",1000,8,36064
8,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '16484714', 'bizesNm': '꼬닭', 'brc...",1000,9,36064
9,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '16604739', 'bizesNm': '푸라닭치킨', '...",1000,10,36064
10,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '16728435', 'bizesNm': '오태식해바라기치킨...",1000,11,36064
11,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '17014298', 'bizesNm': '봉이치킨', 'b...",1000,12,36064
12,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '17142954', 'bizesNm': '노랑통닭', 'b...",1000,13,36064
13,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '17430609', 'bizesNm': '누구나홀딱반한닭'...",1000,14,36064
14,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '17504547', 'bizesNm': '가마치통닭', '...",1000,15,36064
15,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '17616920', 'bizesNm': '60계경기', '...",1000,16,36064
16,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '17847228', 'bizesNm': '신한국통닭', '...",1000,17,36064
17,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '17915858', 'bizesNm': '미이통닭', 'b...",1000,18,36064
18,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '18114669', 'bizesNm': '또봉이통닭', '...",1000,19,36064
19,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '18354009', 'bizesNm': '오늘통닭', 'b...",1000,20,36064
20,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '19991844', 'bizesNm': '호치킨', 'br...",1000,21,36064
21,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '20158282', 'bizesNm': '아주커', 'br...",1000,22,36064
22,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '20304765', 'bizesNm': '닭&주', 'br...",1000,23,36064
23,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '20450480', 'bizesNm': '꾸바꾸바치킨점',...",1000,24,36064
24,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '20609325', 'bizesNm': '대왕가마솥', '...",1000,25,36064
25,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '21867919', 'bizesNm': '한경멕시칸치킨',...",1000,26,36064
26,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '22092363', 'bizesNm': '교촌치킨', 'b...",1000,27,36064
27,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '23180454', 'bizesNm': '광계토바베큐치킨'...",1000,28,36064
28,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '23395927', 'bizesNm': '또래오래', 'b...",1000,29,36064
29,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '25259031', 'bizesNm': '오븐에빠진닭', ...",1000,30,36064
30,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '25551235', 'bizesNm': '또봉이통닭', '...",1000,31,36064
31,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '25789400', 'bizesNm': '맥코이치킨', '...",1000,32,36064
32,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '26069091', 'bizesNm': '네네치킨', 'b...",1000,33,36064
33,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '26205307', 'bizesNm': '비에이치신평', ...",1000,34,36064
34,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '26205307', 'bizesNm': '비에이치신평', ...",1000,34,36064
35,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '28488294', 'bizesNm': 'BBQ치킨올리브떡...",1000,36,36064
36,소상공인시장진흥공단 주요상권내 상가업소정보,"[상가업소번호, 상호명, 지점명, 상권업종대분류코드, 상권업종대분류명, 상권업종중분...",202206,00,NORMAL SERVICE,"[{'bizesId': '9148230', 'bizesNm': '맛꼬방치킨', 'b...",1000,37,36064

한 단계 더 내려가기! (body-items)

In [25]:
pd.json_normalize(chick[0]['body']['items'])

,bizesId,bizesNm,brchNm,indsLclsCd,indsLclsNm,indsMclsCd,indsMclsNm,indsSclsCd,indsSclsNm,ksicCd,...,bldMngNo,bldNm,rdnmAdr,oldZipcd,newZipcd,dongNo,flrNo,hoNo,lon,lat
0,10027626,장모님치킨가창점,가창점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2771031024101200004036858,,대구광역시 달성군 가창면 가창동로 6,711861,42938,,1,,128.644459,35.782663
1,10098244,짱구피자치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4125010300102680011008557,,경기도 동두천시 못골로 30,483030,11320,,,,127.065903,37.901262
2,10099459,쭈노치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4157025324105380008019970,,경기도 김포시 고촌읍 장차로13번길 18,415811,10126,,1,,126.769859,37.603752
3,10136167,치킨뱅이,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4213011000108300006022278,,강원도 원주시 금불3길 5,220938,26423,,1,,127.932025,37.348358
4,10136346,치킨월드율량점,율량점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4311111500108060000045239,,충청북도 청주시 청원구 공항로138번길 53,363818,28328,,1,,127.487586,36.669816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,11927120,두두두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4719034028104640013062144,,경상북도 구미시 해평면 강동로 1671,730873,39154,,1,,128.390989,36.199637
996,11927310,호식이두마리치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4272025029104520007040192,,강원도 홍천군 홍천읍 남산강변로 32,250930,25149,,1,,127.882012,37.685865
997,11927491,또봉이치킨,,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2820010200100690027020930,,인천광역시 남동구 풀무로 9-2,405230,21510,,1,,126.709187,37.469419
998,11927616,투마리치킨하늘도시점,하늘도시점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,2811014600100330008000001,,인천광역시 중구 운중로 85-1,400811,22359,,1,,126.542880,37.493596
999,11927757,노랑통닭,구리수택점,Q,음식,Q05,닭/오리요리,Q05A08,후라이드/양념치킨,I56193,...,4131010500104480006008791,구리신성미소지움,경기도 구리시 이문안로 81,471030,11941,101,1,,127.140380,37.592408

In [ ]:
pd.json_normalize(chick[0]['body']['items'])