In [11]:
import requests
import pandas as pd

In [13]:
servicekey = "cNx+1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO/U+UhQqKv2E4WScQrT/mI1hrZR4ayBRqtIaKHC3BywjHiX3w=="
url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
payload = dict(servicekey = servicekey, divId = "indsSclsCd", key = "I21006", numOfRows = 10, pageNo = 1, type = "json")
r = requests.get(url, params=payload)
data = r.json()
print(r.url)
print(r.status_code)
response = r.json()

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=10&pageNo=1&type=json
200

In [29]:
result = {}
for item in response['body']['items']:
    for key, value in zip(response['header']['columns'], item.values()):
        result.setdefault(key, []).append(value)

In [30]:
df = pd.DataFrame(result)
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800006500,김종용누룽지통닭,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1120010700100190046019611,행당동1,서울특별시 성동구 마조로5길 7,133817,04760,,2,,127.040371,37.559927
1,MA010120220800007898,코리안숯불닭바베큐,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,4111513900102210027019153,,경기도 수원시 팔달구 세지로 369,442837,16242,,,,127.026567,37.283525
2,MA010120220800009322,페리카나치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1130510100103220025020436,,서울특별시 강북구 도봉로29길 10,142815,01176,,1,,127.027661,37.620729
3,MA010120220800001311,페리카나,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111013700100490000014132,,서울특별시 종로구 삼일대로 434-1,110320,03133,,,,126.988182,37.573538
4,MA010120220800009839,매일치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016700100510000012087,,서울특별시 종로구 율곡로19길 9,110844,03100,,,,127.005411,37.575998
5,MA010120220800010432,팜카페앤드전통차,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111015300101370000017924,피카디리플러스,서울특별시 종로구 돈화문로5가길 1,110808,03139,,6,,126.991227,37.571024
6,MA010120220800012252,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111017500102010004001211,,서울특별시 종로구 종로66길 18,110825,03115,,1,,127.021791,37.574140
7,MA010120220800012332,본투비,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1111016200103200002012561,,서울특별시 종로구 대학로 5,110480,03129,,,,127.001721,37.571592
8,MA010120220800003146,깐부치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56194,...,4121010400113390001000001,아이플렉스상가,경기도 광명시 소하로 81,423051,14316,,1,,126.884017,37.447638
9,MA010120220800012733,둘둘치킨,,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1135010200100580002019598,가운데,서울특별시 노원구 석계로1길 10,139841,01902,,1,,127.064119,37.615633

In [27]:
response.keys()

dict_keys(['header', 'body'])

In [28]:
response['header']['columns']

['상가업소번호',
 '상호명',
 '지점명',
 '상권업종대분류코드',
 '상권업종대분류명',
 '상권업종중분류코드',
 '상권업종중분류명',
 '상권업종소분류코드',
 '상권업종소분류명',
 '표준산업분류코드',
 '표준산업분류명',
 '시도코드',
 '시도명',
 '시군구코드',
 '시군구명',
 '행정동코드',
 '행정동명',
 '법정동코드',
 '법정동명',
 'PNU코드',
 '대지구분코드',
 '대지구분명',
 '지번본번지',
 '지번부번지',
 '지번주소',
 '도로명코드',
 '도로명',
 '건물본번지',
 '건물부번지',
 '건물관리번호',
 '건물명',
 '도로명주소',
 '구우편번호',
 '신우편번호',
 '동정보',
 '층정보',
 '호정보',
 '경도',
 '위도']

# 함수화

In [1]:
import requests
import pandas as pd
import time

In [2]:
def unpack_data(response):
    result = {}
    for item in response['body']['items']:
        for key, value in zip(response['header']['columns'], item.values()):
            result.setdefault(key, []).append(value)
    df = pd.DataFrame(result)       
    return df

In [3]:
page = 1
result_dfs = []
while True:
    url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
    servicekey = "cNx+1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO/U+UhQqKv2E4WScQrT/mI1hrZR4ayBRqtIaKHC3BywjHiX3w=="
    payload = dict(servicekey = servicekey, divId = "indsSclsCd", key = "I21006", numOfRows = 1000, pageNo = page, type = "json")
    r = requests.get(url, params=payload)
    data = r.json()
    print(r.url, end="\r")
    print("\n")
    print(r.status_code, end="\r")
    print("\n")
    response = r.json()
    total_page = (response['body']['totalCount'] // 1000) + 1
    result_dfs.append(unpack_data(response))
    print(f"{page}/{total_page} 수집중", end="\r")
#이런 조건문 센스?가 참 어렵네 
    if page < total_page:
        page += 1
    else:
        break
    time.sleep(0.3)
    
result = pd.concat(result_dfs)    
#drop=True 다시 공부하자 (개념 미숙)
result = result.reset_index(drop=True)
result.to_csv("공공데이터_상권정보_202504.csv", encoding = "utf-8", index=False)

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=1&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=2&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=3&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=4&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=5&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=6&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=7&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=8&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=9&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=10&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=11&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=12&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=13&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=14&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=15&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=16&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=17&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=18&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=19&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=20&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=21&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=22&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=23&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=24&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=25&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=26&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=27&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=28&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=29&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=30&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=31&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=32&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=33&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=34&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=35&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=36&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=37&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=38&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=39&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=40&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=41&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=42&type=json

200

http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong?servicekey=cNx%2B1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO%2FU%2BUhQqKv2E4WScQrT%2FmI1hrZR4ayBRqtIaKHC3BywjHiX3w%3D%3D&divId=indsSclsCd&key=I21006&numOfRows=1000&pageNo=43&type=json

200

In [35]:
total_page = (response['body']['totalCount'] // 1000) + 1
total_page

43

# 전체 소분류 모두 추출하기 (소분류 code + 반복문)

In [5]:
# !pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

#### header
* 몇 번째 행을 '컬럼명'으로 쓸 것인지 정하는 키워드

In [10]:
ori_data = pd.read_excel("./data/소상공인시장진흥공단_상가(상권)정보_업종분류(2302)_및_연계표_v1.0.xlsx", engine='openpyxl', header=[1])

In [9]:
ori_data['소분류코드']

    상가(상권)정보 업종분류(247개)                                                \
                  대분류코드          대분류명 중분류코드              중분류명   소분류코드
0                    G2           소매업  G202  자동차 부품 및 내장품 소매업  G20201
1                    G2           소매업  G202  자동차 부품 및 내장품 소매업  G20202
2                    G2           소매업  G203    모터사이클 및 부품 소매업  G20301
3                    G2           소매업  G204            종합 소매업  G20404
4                    G2           소매업  G204            종합 소매업  G20405
..                  ...           ...   ...               ...     ...
242                  S2  수리 및 개인 서비스업  S209               세탁업  S20902
243                  S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21001
244                  S2  수리 및 개인 서비스업  S210    장례식장 및 관련 서비스업  S21002
245                  S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21101
246                  S2  수리 및 개인 서비스업  S211          기타 개인서비스  S21105


               소분류명
0           타이어 소매업
1        자동차 부품 소매업
2    모터사이클 및 부품 소매업
3              슈퍼마켓
4               편의점
..              ...
242          셀프 빨래방
243            장례식장
244      화장터/묘지/납골당
245            예식장업
246      결혼 상담 서비스업

[247 rows x 6 columns]

## 모든 소상공인 소분류업종이 추출된다.

In [12]:
for code in ori_data['소분류코드']:
    print(code)

G20201
G20202
G20301
G20404
G20405
G20499
G20501
G20502
G20503
G20504
G20505
G20506
G20507
G20508
G20509
G20601
G20602
G20603
G20604
G20701
G20801
G20802
G20803
G20901
G20902
G20903
G20904
G20905
G20906
G20907
G20908
G20909
G20910
G20911
G21001
G21002
G21003
G21099
G21101
G21201
G21202
G21203
G21301
G21302
G21303
G21304
G21305
G21306
G21401
G21402
G21403
G21501
G21502
G21503
G21601
G21602
G21603
G21701
G21801
G21802
G21901
G22001
G22199
G22201
I10101
I10102
I10103
I10104
I10201
I10299
I20101
I20102
I20103
I20104
I20105
I20106
I20107
I20108
I20109
I20110
I20111
I20112
I20113
I20199
I20201
I20202
I20301
I20302
I20303
I20399
I20401
I20402
I20403
I20499
I20501
I20599
I20601
I20701
I20702
I21001
I21002
I21003
I21004
I21005
I21006
I21007
I21008
I21099
I21101
I21102
I21103
I21104
I21201
L10203
M10301
M10302
M10303
M10306
M10307
M10399
M10401
M10402
M10499
M10501
M10502
M10503
M10504
M10599
M10601
M10703
M10901
M10902
M10903
M10904
M10999
M11101
M11201
M11202
M11203
M11204
M11301
M11401
M11502
M11504
N10101
N10201
N10202
N10203
N10301
N10401
N10402
N10403
N10501
N10599
N10703
N10799
N10802
N10805
N10901
N10999
N11001
N11002
N11003
N11004
N11099
N11101
N11102
N11199
P10501
P10601
P10603
P10605
P10607
P10609
P10611
P10613
P10615
P10617
P10619
P10621
P10623
P10625
P10627
P10629
P10701
P10799
Q10101
Q10102
Q10103
Q10104
Q10105
Q10201
Q10202
Q10203
Q10204
Q10205
Q10206
Q10207
Q10208
Q10209
Q10210
Q10211
Q10212
Q10402
R10202
R10306
R10307
R10308
R10309
R10310
R10311
R10312
R10313
R10314
R10316
R10402
R10404
R10405
R10406
R10407
R10408
R10409
R10410
R10414
R10499
S20101
S20201
S20301
S20302
S20401
S20501
S20601
S20602
S20603
S20699
S20701
S20702
S20703
S20801
S20802
S20803
S20901
S20902
S21001
S21002
S21101
S21105

In [ ]:
for code, name in zip(ori_data['소분류코드'], ori_data['소분류명']):
    page = 1
    result_dfs = []
    while True:
        url = "http://apis.data.go.kr/B553077/api/open/sdsc2/storeListInUpjong"
        servicekey = "cNx+1qrXIfATijXRStPn7A5nRbqTbMX7a6hHqO/U+UhQqKv2E4WScQrT/mI1hrZR4ayBRqtIaKHC3BywjHiX3w=="
        payload = dict(servicekey = servicekey, divId = "indsSclsCd", key = code, numOfRows = 1000, pageNo = page, type = "json")
        r = requests.get(url, params=payload)
        data = r.json()
        print(r.url, end="\r")
        print(r.status_code, end="\r")
        response = r.json()
        total_page = (response['body']['totalCount'] // 1000) + 1
        result_dfs.append(unpack_data(response))
        print(f"{page}/{total_page} 수집중", end="\r")
    #이런 조건문 센스?가 참 어렵네 
        if page < total_page:
            page += 1
        else:
            break
        time.sleep(0.3)

    result = pd.concat(result_dfs)    
    #drop=True 다시 공부하자 (개념 미숙)
    result = result.reset_index(drop=True)
    result.to_csv(f"공공데이터_{name}_상권정보_202504.csv", encoding = "utf-8", index=False)